var labelArray_it_it = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "Connessioni" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "Eventi" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "Menu",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "Importa connessione" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "Apri log VPN" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "Guida in linea" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "Informazioni" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "Esci" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "Annulla autenticazione", "text": "Annulla" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "Disattiva connessione", "text": "Disconnetti" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "Annulla importazione certificato", "text": "Annulla" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "Abilita connessione", "text": "Connetti" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "Importa un file di connessione",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "Importa connessione" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "Modifica connessione" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "Connessione automatica", "text": "Connessione automatica" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "Elimina" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "Rinomina" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "Cancella credenziali" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "Connessioni" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "Autenticazione utente" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "Accedi con il metodo preferito" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "Salva nome utente e password" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "Accedi" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "Connessione",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "Reti",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "Sicurezza",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "Monitora connessione" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "Attendere - Instaurazione della connessione in corso..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "Attendere - Recupero dei dettagli della connessione in corso..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "Per istruzioni su come creare un profilo di accesso remoto per Sophos Connect su XG Firewall, leggere le seguenti informazioni:" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Crea profilo di Sophos Connect", "text": "Crea profilo di Sophos Connect" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "Importa credenziali del certificato" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "L'autenticazione IKE di questa connessione richiede un certificato e una chiave privata.  Selezionare un file PKCS#12 da importare e immettere la password utilizzata per cifrare il file." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "Inserire password",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "Importa un file PKCS#12",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "Importa file PKCS#12" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "Nessun accesso a Internet. Attendere. Verrà effettuato un nuovo tentativo di connessione una volta ripristinato l'accesso a Internet." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "Generati" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "Descrizione" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "Cancella pagina Eventi", "text": "Cancella eventi" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. Tutti i diritti riservati." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "Visualizza informazioni legali",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "Informazioni legali" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "Versioni" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Servizio Sophos Connect" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "Servizio strongSwan" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "Risoluzione dei problemi" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "Genera report per il supporto tecnico", "text": "Genera report per il supporto tecnico" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Apri forum della Community Sophos",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "Forum della Community" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "Nome connessione" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "Gateway" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "ID IKE remoto" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "ID IKE locale" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "Connesso/a" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "IP locale" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "IP del gateway" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "Indirizzo IP virtuale" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "Server DNS" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "Suffissi DNS" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "Rete remota" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "Reti remote" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "Byte ricevuti" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "Byte trasmessi" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "Pacchetti ricevuti" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "Pacchetti trasmessi" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "Nessuna SA (Security Association) IPsec attiva" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "Algoritmo di cifratura e dimensioni della chiave" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "Algoritmo di integrità" } ],
  [ SC_TID_MONITOR_PRF, {"text": "Funzione pseudocasuale" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Gruppo Diffie-Hellman" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "Prossima reimpostazione chiave" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "Autenticazione in corso..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "Esiste già una connessione con questo nome. Se si decide di continuare, la connessione esistente verrà sovrascritta. Continuare?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "Esiste una connessione con questo nome. Selezionare un'alternativa" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "Cancellare le credenziali dell'utente?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "Errore durante l'importazione del file" } ],
  [ SC_TID_DAY, {"text": "giorno" } ],
  [ SC_TID_DAYS, {"text": "giorni" } ],
  [ SC_TID_HOUR, {"text": "ora" } ],
  [ SC_TID_HOURS, {"text": "ore" } ],
  [ SC_TID_MINUTE, {"text": "minuto" } ],
  [ SC_TID_MINUTES, {"text": "minuti" } ],
  [ SC_TID_SECOND, {"text": "secondo" } ],
  [ SC_TID_SECONDS, {"text": "secondi" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "Attendere. La connessione verrà ritentata a breve" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "VPN SSL" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "Compressione" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "Tipo di VPN" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "Algoritmo di cifratura" } ],
  [ SC_TID_TRUE, {"text": "Vero" } ],
  [ SC_TID_FALSE, {"text": "Falso" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "Aggiorna Criterio" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "Aggiornare il criterio per la connessione attuale?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "Criterio di aggiornamento" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "Criterio di provisioning SSL" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "Connetti al criterio di download" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "L'utente ha continuato dopo l'avviso di sicurezza sul certificato" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "L'utente non ha continuato dopo l'avviso di sicurezza sul certificato" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "Servizio OpenVPN" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "Apri la pagina dei crediti",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "Crediti per i software open source" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "Immetti i caratteri che vedi nell'immagine qui sopra",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "Immetti i caratteri che vedi nell'immagine qui sotto",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "Aggiorna" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "La connessione non è privata" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "Continua al server (opzione non sicura)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "Ignora certificato SSL del server" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "Il certificato di sicurezza del server non è ritenuto attendibile dal sistema operativo del computer. Questo potrebbe essere dovuto a una configurazione errata o a un tentativo da parte dell'autore di un attacco di intercettare la tua connessione." } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "È possibile che l'autore di un attacco stia cercando di rubare le tue informazioni (ad es. password, messaggi o dati di carta di credito)" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "Forza nuovo accesso con SSO" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "Inserisci un valore valido per la porta del portale VPN" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "Il SSO non è configurato. Contatta il tuo amministratore" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "Nome utente e password" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "Nome utente " }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "Password" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "Nuovo token o nuova one-time password" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "OPPURE" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "Single Sign-On (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "Single Sign-On (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "Porta del portale VPN" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "Modifica la porta solo se richiesto dall’amministratore" }],
];
