var labelArray_pt_br = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "Conexões" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "Eventos" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "Menu",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "Importar conexão" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "Abrir log de VPN" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "Ajuda" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "Informações" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "Sair" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "Cancelar autenticação", "text": "Cancelar" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "Desabilitar conexão", "text": "Desconectar" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "Cancelar importação de certificado", "text": "Cancelar" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "Habilitar conexão", "text": "Conectar" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "Importar um arquivo de conexão",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "Importar conexão" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "Editar conexão" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "Conexão automática", "text": "Conexão automática" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "Deletar" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "Renomear" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "Limpar credenciais" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "Conexões" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "Autenticar usuário" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "Iniciar sessão com o método preferido" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "Salvar nome de usuário e senha" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "Iniciar sessão" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "Conexão",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "Redes",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "Segurança",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "Monitor de conexão" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "Aguarde - estabelecendo conexão..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "Aguarde - coletando detalhes da conexão..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "Para obter instruções sobre como criar um perfil de acesso remoto para o Sophos Connect no XG Firewall, leia as seguintes informações:" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Criar Perfil do Sophos Connect", "text": "Criar Perfil do Sophos Connect" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "Importar credenciais de certificado" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "A autenticação IKE desta conexão requer certificado e chave privada.  Selecione um arquivo PKCS#12 para importar e insira a senha utilizada para encriptar o arquivo." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "Inserir senha",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "Importar um arquivo PKCS#12",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "Importar arquivo PKCS#12" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "Sem acesso à Internet. Aguarde. Tentaremos uma nova conexão quando o acesso à Internet for restaurado." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "Ocorrido" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "Descrição" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "Página Limpar eventos", "text": "Limpar eventos" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. Todos os direitos reservados." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "Ver Detalhes legais",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "Detalhes legais" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "Versões" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Serviço Sophos Connect" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "Serviço strongSwan" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "Solução de problemas" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "Gerar relatório de suporte técnico", "text": "Gerar relatório de suporte técnico" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Abrir o fórum da comunidade Sophos",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "Fórum da comunidade" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "Nome da Conexão" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "Gateway" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "ID IKE remoto" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "ID IKE local" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "Conectado" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "IP local" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "IP de Gateway" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "Endereço de IP virtual" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "Servidores de DNS" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "Sufixos de DNS" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "Rede Remota" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "Redes Remotas" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "Bytes Recebidos" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "Bytes Transmitidos" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "Pacotes Recebidos" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "Pacotes Transmitidos" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "IPsec SA (Security Association) não ativado" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "Algoritmo de encriptação e tamanho da chave" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "Algoritmo de integridade" } ],
  [ SC_TID_MONITOR_PRF, {"text": "Funcionalidade pseudoaleatória" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Grupo Diffie-Hellman" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "Próximo rechaveamento" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "Autenticando..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "Já existe uma conexão com o mesmo nome. Caso você continue, a conexão existente será substituída. Continuar?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "Já existe uma conexão com esse nome. Escolha outro" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "Limpar as credenciais do usuário?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "Erro de importação de arquivo" } ],
  [ SC_TID_DAY, {"text": "dia" } ],
  [ SC_TID_DAYS, {"text": "dias" } ],
  [ SC_TID_HOUR, {"text": "hora" } ],
  [ SC_TID_HOURS, {"text": "horas" } ],
  [ SC_TID_MINUTE, {"text": "minuto" } ],
  [ SC_TID_MINUTES, {"text": "minutos" } ],
  [ SC_TID_SECOND, {"text": "segundo" } ],
  [ SC_TID_SECONDS, {"text": "segundos" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "Aguarde. Tentaremos uma nova conexão em breve" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "SSL VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "Compressão" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "Tipo de VPN" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "Algoritmo de encriptação" } ],
  [ SC_TID_TRUE, {"text": "Verdadeiro" } ],
  [ SC_TID_FALSE, {"text": "Falso" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "Atualizar Política" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "Atualizar a política da conexão atual?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "Atualizando política" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "Política de provisionamento de SSL" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "Conectar para baixar política" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "O usuário continuou após o aviso de segurança de certificado" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "O usuário parou após o aviso de segurança de certificado" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "Serviço OpenVPN" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "Abrir página de créditos",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "Créditos de software de código aberto" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "Insira os caracteres mostrados na imagem acima",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "Insira os caracteres mostrados na imagem abaixo",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "Atualizar" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "A sua conexão não é privada" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "Continuar para o servidor (não seguro)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "Ignorar o Certificado SSL do Servidor" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "O certificado de segurança do servidor não é confiável pelo sistema operacional do seu computador. Isso pode ser causado por uma configuração incorreta ou um invasor que interceptou a sua conexão." } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "Invasores podem estar tentando roubar suas informações (por exemplo, senhas, mensagens ou dados de cartões de crédito)" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "Forçar novo login com SSO" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "Insira um valor válido para a porta do Portal de VPN" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO não está configurado. Entre em contato com o administrador" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "Nome de usuário e senha" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "Nome de usuário " }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "Senha" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "Novo token ou senha de uso único" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "OU" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "Logon único (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "Logon único (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "Porta do portal de VPN" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "Edite a porta somente se o administrador solicitar" }],
];
