var labelArray_de_de = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "Verbindungen" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "Ereignisse" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "Menü",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "Verbindung importieren" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "VPN-Protokoll öffnen" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "Hilfe" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "Über" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "Beenden" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "Authentifizierung abbrechen", "text": "Abbrechen" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "Verbindung deaktivieren", "text": "Verbindung trennen" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "Zertifikatimport abbrechen", "text": "Abbrechen" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "Verbindung aktivieren", "text": "Verbinden" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "Verbindungsdatei importieren",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "Verbindung importieren" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "Verbindung bearbeiten" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "Automatisch verbinden", "text": "Automatisch verbinden" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "Löschen" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "Umbenennen" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "Anmeldeinformationen löschen" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "Verbindungen" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "Benutzer authentifizieren" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "Mit bevorzugter Methode anmelden" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "Benutzername und Kennwort speichern" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "Anmelden" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "Verbindung",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "Netzwerke",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "Sicherheit",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "Verbindung überwachen" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "Einen Moment, die Verbindung wird hergestellt ..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "Einen Moment, Verbindungsdetails werden abgerufen ..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "Eine Anleitung, wie Sie ein XG-Firewall-Fernzugriffsprofil für Sophos Connect erstellen, finden Sie hier:" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Sophos Connect-Profil erstellen", "text": "Sophos Connect-Profil erstellen" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "Zertifikat-Anmeldeinformationen importieren" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "Für die IKE-Authentifizierung dieser Verbindung sind ein Zertifikat und ein privater Schlüssel erforderlich.  Wählen Sie eine PKCS#12-Datei für den Import aus und geben Sie das für die Verschlüsselung der Datei verwendete Kennwort ein." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "Kennwort eingeben",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "PKCS#12-Datei importieren",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "PKCS#12-Datei importieren" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "Keine Internetverbindung. Bitte warten. Es wird erneut versucht eine Verbindung aufzubauen, wenn der Internetzugang wiederhergestellt ist." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "Aufgetreten" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "Beschreibung" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "Ereignis-Seite leeren", "text": "Ereignisse löschen" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. Alle Rechte vorbehalten." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "Siehe „Rechtliche Hinweise“",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "Rechtliche Hinweise" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "Versionen" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Sophos Connect-Dienst" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "strongSwan-Dienst" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "Fehlersuche" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "Technischen Supportbericht erstellen", "text": "Technischen Supportbericht erstellen" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Sophos Community-Forum öffnen",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "Community-Forum" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "Verbindungsname" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "Gateway" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "Remote IKE-ID" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "Lokale IKE-ID" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "Verbunden" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "Lokale IP" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "Gateway-IP" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "Virtuelle IP-Adresse" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "DNS-Server" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "DNS-Suffixe" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "Entferntes Netzwerk" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "Entfernte Netzwerke" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "Erhaltene Bytes" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "Übertragene Bytes" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "Empfangene Pakete" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "Übertragene Pakete" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "Keine aktive IPsec SA (Security Association)" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "Verschlüsselungsalgorithmus und Schlüssellänge" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "Integritätsalgorithmus" } ],
  [ SC_TID_MONITOR_PRF, {"text": "Pseudozufallsfunktion" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Diffie-Hellman-Gruppe" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "Nächster Rekey" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "Authentifizierung läuft ..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "Eine Verbindung mit diesem Namen ist bereits vorhanden. Wenn Sie fortfahren, wird die vorhandene Verbindung überschrieben. Weiter?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "Es gibt bereits eine Verbindung mit diesem Namen. Wählen Sie einen anderen Namen aus" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "Benutzer-Anmeldeinformationen löschen?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "Fehler beim Importieren der Datei" } ],
  [ SC_TID_DAY, {"text": "Tag" } ],
  [ SC_TID_DAYS, {"text": "Tage" } ],
  [ SC_TID_HOUR, {"text": "Stunde" } ],
  [ SC_TID_HOURS, {"text": "Stunden" } ],
  [ SC_TID_MINUTE, {"text": "Minute" } ],
  [ SC_TID_MINUTES, {"text": "Minuten" } ],
  [ SC_TID_SECOND, {"text": "Sekunde" } ],
  [ SC_TID_SECONDS, {"text": "Sekunden" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "Bitte warten. Es wird in Kürze versucht die Verbindung wieder aufzubauen" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "SSL-VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "Komprimierung" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "VPN-Typ" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "Verschlüsselungsalgorithmus" } ],
  [ SC_TID_TRUE, {"text": "Richtig" } ],
  [ SC_TID_FALSE, {"text": "Falsch" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "Richtlinie aktualisieren" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "Richtlinie für die aktuelle Verbindung aktualisieren?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "Richtlinie wird aktualisiert" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "SSL-Bereitstellungsrichtlinie" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "Verbindung zum Herunterladen herstellen" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "Benutzer machte nach Zertifikats-Sicherheitswarnung weiter" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "Benutzer machte nach Zertifikats-Sicherheitswarnung nicht weiter" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "OpenVPN-Dienst" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "Die Seite „Credits“ Öffnen",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "Credits für Open-Source-Software" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "Geben Sie die Zeichen ein, die in der Abbildung oben angezeigt werden",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "Geben Sie die Zeichen ein, die in der Abbildung unten angezeigt werden",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "Aktualisieren" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "Ihre Verbindung ist nicht privat" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "Weiter zum Server (unsicher)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "Server-SSL-Zertifikat umgehen" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "Das Sicherheitszertifikat des Servers wird vom Betriebssystem Ihres Computers als nicht vertrauenswürdig eingestuft. Dies kann durch eine falsche Konfiguration oder einen Angreifer verursacht werden, der Ihre Verbindung abfängt." } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "Angreifer könnten versuchen, Ihre Informationen zu stehlen (z. B. Passwörter, Nachrichten oder Kreditkartendaten)" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "SSO-Wiederanmeldung erzwingen" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "Geben Sie einen gültigen Wert für VPN-Portal-Port ein" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO ist nicht konfiguriert. Bitte wenden Sie sich an Ihren Administrator" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "Benutzername und Kennwort" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "Benutzername" }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "Kennwort" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "Neues Token oder Einmalkennwort" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "ODER" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "Single-Sign-On (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "Single-Sign-On (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "VPN-Portal-Port" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "Ändern Sie den Port nur nach Aufforderung durch Ihren Administrator" }],
];
