var labelArray_ko_kr = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "연결" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "이벤트" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "메뉴",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "연결 가져오기" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "VPN 로그 열기" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "도움말" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "소개" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "종료" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "인증 취소", "text": "취소" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "연결 비활성화", "text": "연결 해제" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "인증서 가져오기 취소", "text": "취소" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "연결 활성화", "text": "연결" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "연결 파일 가져오기",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "연결 가져오기" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "연결 편집" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "자동 연결", "text": "자동 연결" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "삭제" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "이름 바꾸기" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "자격 증명 지우기" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "연결" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "사용자 인증" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "선호 방법으로 로그인" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "사용자 이름 및 암호 저장" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "로그인" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "연결",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "네트워크",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "보안",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "모니터 연결" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "잠시 기다려 주십시오 - 연결을 설정하는 중..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "잠시 기다려 주십시오 - 연결 세부 정보를 수집하는 중..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "XG Firewall에 Sophos Connect용 원격 액세스 프로파일을 생성하는 방법에 대한 지침은 다음 정보를 참조하십시오." } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Sophos Connect 프로파일 생성", "text": "Sophos Connect 프로파일 생성" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "인증서 자격 증명 가져오기" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "이 연결의 IKE 인증에는 인증서와 프라이빗 키가 필요합니다.  가져올 PKCS#12 파일을 선택하고, 파일 암호화에 사용된 암호를 입력하십시오." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "암호 입력",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "PKCS#12 파일 가져오기",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "PKCS#12 파일 가져오기" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "인터넷에 액세스할 수 없습니다. 기다려 주십시오. 인터넷 액세스가 복원되면 다시 연결을 시도합니다." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "발생일시" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "설명" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "이벤트 지우기 페이지", "text": "이벤트 지우기" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. All rights reserved." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "법적 세부 정보 보기",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "법적 세부 정보" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "버전" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Sophos Connect 서비스" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "strongSwan 서비스" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "문제 해결" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "기술 지원 보고서 생성", "text": "기술 지원 보고서 생성" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Sophos Community 포럼 열기",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "커뮤니티 포럼" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "연결 이름" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "게이트웨이" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "원격 IKE ID" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "로컬 IKE ID" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "연결됨" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "로컬 IP" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "게이트웨이 IP" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "가상 IP 주소" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "DNS 서버" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "DNS 접미사" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "원격 네트워크" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "원격 네트워크" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "수신된 바이트" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "전송된 바이트" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "수신된 패킷" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "전송된 패킷" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "활성 IPsec SA(보안 연결)가 없음" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "암호화 알고리즘 및 키 크기" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "무결성 알고리즘" } ],
  [ SC_TID_MONITOR_PRF, {"text": "의사 무작위 함수" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "디피-헬먼 그룹" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "다음 키 다시 지정" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "인증하는 중..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "이 이름의 연결이 이미 있습니다. 계속할 경우 기존 연결이 덮어쓰입니다. 계속하시겠습니까?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "이 이름의 연결이 이미 있습니다. 다른 이름을 선택하십시오" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "사용자 자격 증명을 지우시겠습니까?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "파일 가져오기 오류" } ],
  [ SC_TID_DAY, {"text": "일" } ],
  [ SC_TID_DAYS, {"text": "일" } ],
  [ SC_TID_HOUR, {"text": "시간" } ],
  [ SC_TID_HOURS, {"text": "시간" } ],
  [ SC_TID_MINUTE, {"text": "분" } ],
  [ SC_TID_MINUTES, {"text": "분" } ],
  [ SC_TID_SECOND, {"text": "초" } ],
  [ SC_TID_SECONDS, {"text": "초" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "기다려 주십시오. 곧 연결 다시 시도" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "SSL VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "압축" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "VPN 유형" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "암호화 알고리즘" } ],
  [ SC_TID_TRUE, {"text": "참" } ],
  [ SC_TID_FALSE, {"text": "거짓" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "정책 업데이트" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "현재 연결에 대한 정책을 업데이트하시겠습니까?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "정책 업데이트 중" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "SSL 프로비저닝 정책" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "연결하여 정책 다운로드" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "인증서 보안 경고 후 계속한 사용자" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "인증서 보안 경고 후 중단한 사용자" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "OpenVPN 서비스" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "크레딧 페이지 열기",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "소스 소프트웨어 크레딧 열기" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "위의 이미지에 표시된 문자 입력",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "아래의 이미지에 표시된 문자 입력",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "새로 고침" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "연결이 전용선이 아닙니다." } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "서버로 계속(안전하지 않음)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "서버 SSL 인증서 우회" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "귀하의 컴퓨터 운영 체제가 서버의 보안 인증서를 신뢰하지 않습니다. 잘못된 구성 또는 공격자의 연결 가로채기가 그 원인일 수 있습니다." } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "공격자가 귀하의 정보(예: 암호, 메시지 또는 신용카드 세부 정보)를 탈취하려 시도했을 수 있습니다." }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "SSO 재로그인 적용" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "VPN 포털 포트에 유효한 값을 입력하십시오." }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO가 구성되지 않았습니다. 관리자에게 문의하십시오." }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "사용자 이름과 암호" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "사용자 이름 " }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "암호" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "새 토큰 또는 일회용 암호" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "또는" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "싱글 사인온(SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "싱글 사인온(SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "VPN 포털 포트" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "관리자가 요청하는 경우에만 포트를 편집합니다." }],
];
