var labelArray_en_us = 
[
  [ SC_TID_PRODUCT_NAME, {"elemId": "", "text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "Connections" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "Events" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "Menu" } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "Import connection" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "View VPN log" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "Help" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "About" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "Quit" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "Cancel authentication", "text": "Cancel" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "Disable connection", "text": "Disconnect" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "Cancel certificate import", "text": "Cancel" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "Enable connection", "text": "Connect" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "Import a connection file" } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "Import connection" } ],
  [ SC_TID_EDIT_MENU_ICON, {"elemId": "", "text": "Edit connection" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "Auto-connect", "text": "Auto-connect" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "Delete" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "Rename" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "Clear credentials" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "Connections" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "Authenticate user" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "Sign in with preferred method" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "" } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "" } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "" } ],
  [SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, { "elemId": "saveCredentialsLabel", "text": "Remember user name and password" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "Sign in" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "Connection" } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "Networks" } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "Security" } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "Monitor connection" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "Please wait - establishing connection..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "Please wait - gathering connection details..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "For instructions on how to create a remote access profile for Sophos Connect on XG Firewall, see the following information:" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Create Sophos Connect profile", "text": "Create Sophos Connect profile" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "Import certificate credentials" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "IKE authentication of this connection requires a certificate and private key.  Please select a PKCS#12 file for import and enter the password which was used to encrypt the file." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "Enter password" } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "Import a PKCS#12 file" } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "Import PKCS#12 file" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "No internet access. Please wait. We'll try to connect again when internet access is restored." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "Occurred" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "Description" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "Clear Events page", "text": "Clear events" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. All rights reserved." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "See Legal Details" } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "Legal Details" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "Versions" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Sophos Connect service" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "strongSwan service" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "Troubleshooting" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "Generate technical support report", "text": "Generate technical support report" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Open Sophos Community forum" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "Community forum" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"elemId": "", "text": "Connection name" } ],
  [ SC_TID_MONITOR_GATEWAY, {"elemId": "", "text": "Gateway" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"elemId": "", "text": "Remote IKE ID" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"elemId": "", "text": "Local IKE ID" } ],
  [ SC_TID_MONITOR_CONNECTED, {"elemId": "", "text": "Connected" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"elemId": "", "text": "Local IP" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"elemId": "", "text": "Gateway IP" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"elemId": "", "text": "Virtual IP address" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"elemId": "", "text": "DNS servers" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"elemId": "", "text": "DNS suffixes" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"elemId": "", "text": "Remote network" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"elemId": "", "text": "Remote networks" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"elemId": "", "text": "Bytes received" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"elemId": "", "text": "Bytes transmitted" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"elemId": "", "text": "Packets received" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"elemId": "", "text": "Packets transmitted" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"elemId": "", "text": "No active IPsec SA (Security Association)" } ],
  [ SC_TID_MONITOR_IKE, {"elemId": "", "text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"elemId": "", "text": "Encryption algorithm and key size" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"elemId": "", "text": "Integrity algorithm" } ],
  [ SC_TID_MONITOR_PRF, {"elemId": "", "text": "Pseudorandom function" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"elemId": "", "text": "Diffie-Hellman group" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"elemId": "", "text": "Next rekey" } ],
  [ SC_TID_MONITOR_IPSEC, {"elemId": "", "text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"elemId": "", "text": "Authenticating..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"elemId": "", "text": "A connection with this name already exists. If you continue, the existing connection will be overwritten. Continue?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"elemId": "", "text": "A connection exists with this name. Please choose another" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"elemId": "", "text": "Clear the user credentials?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"elemId": "", "text": "File import error" } ],
  [ SC_TID_DAY, {"elemId": "", "text": "day" } ],
  [ SC_TID_DAYS, {"elemId": "", "text": "days" } ],
  [ SC_TID_HOUR, {"elemId": "", "text": "hour" } ],
  [ SC_TID_HOURS, {"elemId": "", "text": "hours" } ],
  [ SC_TID_MINUTE, {"elemId": "", "text": "minute" } ],
  [ SC_TID_MINUTES, {"elemId": "", "text": "minutes" } ],
  [ SC_TID_SECOND, {"elemId": "", "text": "second" } ],
  [ SC_TID_SECONDS, {"elemId": "", "text": "seconds" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "Please wait. We'll retry connection shortly" } ],
  [ SC_TID_MONITOR_SSLVPN, {"elemId": "", "text": "SSL VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"elemId": "", "text": "Compression" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"elemId": "", "text": "VPN type" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"elemId": "", "text": "Encryption algorithm" } ],
  [ SC_TID_TRUE, {"elemId": "", "text": "True" } ],
  [ SC_TID_FALSE, {"elemId": "", "text": "False" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "Update policy" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"elemId": "", "text": "Update policy for the current connection?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"elemId": "", "text": "Updating policy" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"elemId": "", "text": "SSL Provisioning policy" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"elemId": "", "text": "Connect to download policy" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"elemId": "", "text": "User continued after certificate security warning" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"elemId": "", "text": "User stopped after certificate security warning" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "OpenVPN service" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "Open Credits page" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "Open source software credits" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "Enter captcha shown in image" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "Enter the characters shown in the image below" } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "Refresh" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"elemId": "", "text": "Your connection is not private" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "Continue to server (unsafe)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "Bypass Server SSL Certificate" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "Server's security certificate is not trusted by your computer's operating system. This may be caused by incorrect configuration or an attacker intercepting your connection." } ],
  [ SC_TID_SSL_CONNECTION_ERROR, {"elemId": "sslErrText", "text": "Attackers might be trying to steal your information (for example, passwords, messages or credit card details)" } ],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "Force SSO re-login" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "Enter a valid value for VPN portal port" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO isn't configured. Please contact your administrator" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "User name and password" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "User name" }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "Password" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "New token or one-time password" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "OR" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "Single sign-on (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "Single sign-on (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "VPN portal port" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "Only edit the port if your administrator requests" }],
 ];
