var labelArray_fr_fr = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "Connexions" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "Événements" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "Menu",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "Importer la connexion" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "Ouvrir le journal VPN" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "Aide" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "À propos" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "Quitter" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "Annuler l’authentification", "text": "Annuler" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "Désactiver la connexion", "text": "Déconnecter" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "Annuler l’importation du certificat", "text": "Annuler" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "Activer la connexion", "text": "Connecter" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "Importer un fichier de connexion",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "Importer la connexion" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "Modifier la connexion" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "Auto-connecter", "text": "Auto-connecter" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "Supprimer" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "Renommer" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "Effacer les codes d’accès" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "Connexions" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "Authentifier l’utilisateur" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "Se connecter avec la méthode préférée" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "Enregistrer le nom d’utilisateur et le mot de passe" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "Connexion" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "Connexion",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "Réseaux",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "Sécurité",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "État de la connexion" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "Veuillez patienter - Établissement de la connexion..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "Veuillez patienter - Récupération des informations de connexion..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "Retrouvez plus de renseignements sur la création d’un profil d’accès à distance pour Sophos Connect sur XG Firewall ci-dessous :" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Créer un profil Sophos Connect", "text": "Créer un profil Sophos Connect" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "Importer les codes d’accès du certificat" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "Un certificat et une clé privée sont nécessaires à l’authentification IKE de cette connexion.  Veuillez sélectionnez un fichier PKCS#12 pour importer et saisir le mot de passe utilisé pour chiffrer le fichier." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "Saisir le mot de passe",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "Importer un fichier PKCS#12",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "Importer le fichier PKCS#12" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "Aucun accès Internet. Veuillez patienter. Nous tenterons une nouvelle connexion dès le rétablissement de l’accès à Internet." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "Date" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "Description" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "Effacer la page Événements", "text": "Effacer les événements" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. Tous droits réservés." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "Voir les Informations légales",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "Informations légales" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "Versions" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Service Sophos Connect" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "Service strongSwan" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "Résolution des problèmes" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "Créer un rapport pour le support technique", "text": "Créer un rapport pour le support technique" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Ouvrir le forum Sophos Community",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "Forum Sophos Community" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "Nom de la connexion" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "Passerelle" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "ID IKE distant" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "ID IKE local" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "Connecté" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "IP locale" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "IP de la passerelle" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "Adresse IP virtuelle" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "Serveurs DNS" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "Suffixes DNS" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "Réseau distant" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "Réseaux distants" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "Octets reçus" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "Octets transmis" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "Paquets reçus" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "Paquets transmis" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "Aucune association de sécurité (SA) IPsec active" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "Algorithme de chiffrement et taille de la clé" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "Algorithme d’intégrité" } ],
  [ SC_TID_MONITOR_PRF, {"text": "Fonction pseudo-aléatoire" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Groupe Diffie-Hellman" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "Prochain renouvellement de la clé" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "Authentification..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "Une connexion du même nom existe déjà. Si vous continuez, la connexion existante sera remplacée. Continuer ?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "Une connexion du même nom existe déjà. Veuillez choisir un autre nom" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "Effacer les codes d’accès de l’utilisateur ?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "Erreur d’importation du fichier" } ],
  [ SC_TID_DAY, {"text": "jour" } ],
  [ SC_TID_DAYS, {"text": "jours" } ],
  [ SC_TID_HOUR, {"text": "heure" } ],
  [ SC_TID_HOURS, {"text": "heures" } ],
  [ SC_TID_MINUTE, {"text": "minute" } ],
  [ SC_TID_MINUTES, {"text": "minutes" } ],
  [ SC_TID_SECOND, {"text": "seconde" } ],
  [ SC_TID_SECONDS, {"text": "secondes" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "Veuillez patienter. Nous allons réessayer d’établir la connexion dans les plus brefs délais" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "VPN SSL" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "Compression" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "Type de VPN" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "Algorithme de chiffrement" } ],
  [ SC_TID_TRUE, {"text": "Vrai" } ],
  [ SC_TID_FALSE, {"text": "Faux" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "Mettre à jour une stratégie" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "Mettre à jour la stratégie pour la connexion existante ?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "Mise à jour de la stratégie" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "Stratégie d’approvisionnement SSL" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "Se connecter à la stratégie de téléchargement" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "L’utilisateur a continué après l’avertissement de sécurité du certificat" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "L’utilisateur a arrêté après l’avertissement de sécurité du certificat" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "Service OpenVPN" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "Ouvrir la page Crédits",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "Crédits logiciels Open Source" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "Saisir les caractères indiqués dans l’image ci-dessus",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "Saisir les caractères indiqués dans l’image ci-dessous",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "Actualiser" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "Votre connexion n’est pas privée" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "Continuer vers le serveur (non sécurisé)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "Ignorer le certificat SSL du serveur" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "Le certificat de sécurité du serveur n’est pas approuvé par le système d’exploitation de votre ordinateur. Ceci peut être dû à une configuration incorrecte ou à un cybercriminel qui intercepte votre connexion." } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "Des cybercriminels tentent peut-être de dérober vos informations (par exemple, mots de passe, messages ou informations de carte de crédit)." }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "Forcer la reconnexion via SSO" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "Saisissez une valeur valide pour le port du portail VPN" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO n’est pas configuré. Veuillez contacter votre administrateur" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "Nom d’utilisateur et mot de passe" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "Nom d’utilisateur" }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "Mot de passe" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "Nouveau token ou mot de passe à usage unique" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "OU" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "Authentification unique (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "Authentification unique (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "Port du portail VPN" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "Modifiez le port uniquement si votre administrateur le demande" }],
];
