var labelArray_zh_tw = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "連接" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "事件" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "選單",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "匯入連接" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "開啟 VPN 記錄" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "說明" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "關於" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "退出" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "取消驗證", "text": "取消" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "停用連接", "text": "中斷連線" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "取消憑證匯入", "text": "取消" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "啟用連接", "text": "連接" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "匯入連接檔",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "匯入連接" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "編輯連接" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "自動連接", "text": "自動連接" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "刪除" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "重新命名" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "清除憑證" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "連接" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "驗證使用者" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "使用首選方法登入" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "儲存使用者名稱及密碼" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "登入" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "連線",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "網路",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "安全",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "監控連接" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "請稍候 - 正在建立連接..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "請稍候 - 正在收集連接詳情..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "如需如何在 XG Firewall 上建立 Sophos Connect 遠端存取設定檔的說明，請參閱以下資訊：" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "建立 Sophos Connect 設定檔", "text": "建立 Sophos Connect 設定檔" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "匯入憑證認證" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "此連接的 IKE 驗證需要憑證及私密金鑰。  請選擇要匯入的 PKCS#12 檔案，然後輸入該檔案的加密密碼。" } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "输入密码",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "匯入 PKCS#12 檔案",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "匯入 PKCS#12 檔案" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "連不上網際網路。請稍候。等到網際網路連線恢復後，我們將重新嘗試連線。" } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "發生" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "說明" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "清除事件頁", "text": "清除事件" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited.保留一切權利。" } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "請參閱法律詳情",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "法律詳情" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "版本" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Sophos Connect 服務" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "strongSwan 服務" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "排疑解難故障排除" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "產生技術支援報告", "text": "產生技術支援報告" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Sophos Community 開放論壇",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "社群論壇" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "連線名稱" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "閘道" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "遠端 IKE ID" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "本機 IKE ID" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "已連線" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "本機 IP" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "閘道 IP" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "虛擬 IP 位址" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "DNS 伺服器" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "DNS 附檔名" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "遠端網路" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "遠端網路" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "已接收位元組" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "已傳輸位元組" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "已收到資料包" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "已傳輸資料包" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "無啟用中的 IPsec SA（安全性關聯）" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "加密演算法和金鑰大小" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "完整性演算法" } ],
  [ SC_TID_MONITOR_PRF, {"text": "擬亂函數" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Diffie-Hellman 群組" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "下一步重設金鑰" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "正在驗證..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "擁有此名稱的連接已經存在。若您繼續，將會覆蓋現有連接。是否繼續？" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "此名稱的連接已存在。請選擇其他名稱" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "要清除使用者認證嗎？" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "檔案匯入錯誤" } ],
  [ SC_TID_DAY, {"text": "天" } ],
  [ SC_TID_DAYS, {"text": "天" } ],
  [ SC_TID_HOUR, {"text": "小時" } ],
  [ SC_TID_HOURS, {"text": "小時" } ],
  [ SC_TID_MINUTE, {"text": "分鐘" } ],
  [ SC_TID_MINUTES, {"text": "分钟" } ],
  [ SC_TID_SECOND, {"text": "秒" } ],
  [ SC_TID_SECONDS, {"text": "秒" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "請稍候。我們將重新嘗試連線" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "SSL VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "壓縮" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "VPN 類型" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "加密演算法" } ],
  [ SC_TID_TRUE, {"text": "正確" } ],
  [ SC_TID_FALSE, {"text": "錯誤" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "更新策略" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "要更新當前連線的政策嗎？" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "更新策略" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "SSL 佈建策略" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "連線至下載政策" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "憑證安全警告後使用者繼續操作" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "憑證安全警告後使用者停止操作" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "OpenVPN 服務" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "開啟「來源」頁面",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "開放原始碼軟體來源" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "輸入上圖中所示的字元",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "輸入下圖中所示的字元",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "更新" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "您的連線不是私人的" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "繼續前往伺服器（不安全）" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "略過伺服器 SSL 憑證" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "您的電腦作業系統不信任伺服器安全憑證。這可能因不正確的設定或攻擊者攔截您的連線造成。" } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "攻擊者可能會嘗試竊取您的資訊（例如密碼、訊息或信用卡詳情）" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "強制進行 SSO 重新登入" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "請輸入有效的 VPN 入口網站連接埠值" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "未設定 SSO。請連絡系統管理員" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "使用者名稱和密碼" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "使用者名稱 " }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "密碼" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "新權杖或一次性密碼" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "或" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "單一登入 (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "單一登入 (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "VPN 入口網站連接埠" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "僅在管理員請求時編輯連接埠" }],
];
