var labelArray_zh_cn = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "连接" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "事件" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "菜单",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "导入连接" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "开启 VPN 记录" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "帮助" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "关于" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "退出" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "取消验证", "text": "取消" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "停用连接", "text": "中断连接" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "取消证书导入", "text": "取消" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "启用连接", "text": "连接" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "导入连接文件",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "导入连接" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "编辑连接" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "自动连接", "text": "自动连接" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "删除" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "重命名" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "清除凭据" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "连接" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "验证使用者" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "使用首选方法登录" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "储存用户名称及密码" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "登录" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "连接",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "网络",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "安全",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "监控连接" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "请稍候 - 正在建立连接..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "请稍候 - 正在收集连接详情..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "如需如何在 XG Firewall 上建立 Sophos Connect 远程访问配置文件的说明，请参阅以下信息：" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "建立 Sophos Connect 配置文件", "text": "建立 Sophos Connect 配置文件" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "导入证书凭据" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "此连接的 IKE 验证需要证书及私钥。  请选择要导入的 PKCS#12 文件，然后输入该档案的加密密码。" } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "输入密码",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "导入 PKCS#12 文件",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "导入 PKCS#12 文件" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "连不上因特网。请耐心等待。Internet 访问恢复后，我们将尝试再次连接。" } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "发生时间" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "说明" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "清除事件页", "text": "清除事件" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "版权所有 2019-2025 Sophos Limited。保留所有权利。" } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "请参阅法律详情",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "法律详情" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "版本" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Sophos Connect 服务" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "strongSwan 服务" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "排疑解难" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "产生技术支持报告", "text": "产生技术支持报告" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Sophos Community 开放论坛",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "社区论坛" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "连接名称" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "网关" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "远程 IKE ID" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "本机 IKE ID" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "连接" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "本地 IP" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "网关IP" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "虚拟 IP 地址" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "DNS 服务器" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "DNS 附檔名" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "远程网络" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "远程网络" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "接受的字节" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "传送字节" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "已收到数据报" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "已传输数据报" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "无启用中的 IPsec SA（安全性关联）" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "加密算法和密钥大小" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "完整性算法" } ],
  [ SC_TID_MONITOR_PRF, {"text": "拟乱函数" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Diffie-Hellman 群组" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "下一步重设密钥" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "正在验证..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "拥有此名称的连接已经存在。若您继续，将会覆盖现有连接。是否继续？" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "此名称的连接已存在。请选择其他名称" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "清除用户凭据？" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "文件导入错误" } ],
  [ SC_TID_DAY, {"text": "日" } ],
  [ SC_TID_DAYS, {"text": "天数" } ],
  [ SC_TID_HOUR, {"text": "小时" } ],
  [ SC_TID_HOURS, {"text": "小时" } ],
  [ SC_TID_MINUTE, {"text": "分钟" } ],
  [ SC_TID_MINUTES, {"text": "分钟" } ],
  [ SC_TID_SECOND, {"text": "秒" } ],
  [ SC_TID_SECONDS, {"text": "秒" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "请耐心等待。我们很快将再次尝试连接" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "SSL VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "压缩" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "VPN 类型" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "加密算法" } ],
  [ SC_TID_TRUE, {"text": "True" } ],
  [ SC_TID_FALSE, {"text": "False" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "更新策略" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "更新当前连接的策略？" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "更新策略" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "SSL 设置策略" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "连接并下载策略" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "证书安全警告后用户继续" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "证书安全警告后用户停止" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "OpenVPN 服务" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "打开“信用”页面",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "开源软件信用" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "输入上图中显示的字符",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "输入下图中显示的字符",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "更新" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "您的连接不是专用连接" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "继续连接到服务器 (不安全)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "绕过服务器 SSL 证书" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "服务器的安全证书不受计算机操作系统的信任。这可能是由配置不正确或连接被攻击者侦听造成的。" } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "攻击者可能试图窃取您的信息 (例如，密码、消息或信用卡详细信息)" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "强制要求 SSO 重新登录" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "请输入有效的 VPN 门户端口值" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO 未配置。请联系您的管理员" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "用户名和密码" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "用户名 " }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "密码" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "新的令牌或一次性密码" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "或" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "单一登录 (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "单一登录 (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "VPN 门户 端口" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "仅在管理员请求时编辑端口" }],
];
