var labelArray_ja_jp = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "接続" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "イベント" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "メニュー",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "接続のインポート" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "VPN ログを開く" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "ヘルプ" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "バージョン情報" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "終了" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "認証のキャンセル", "text": "キャンセル" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "接続の無効化", "text": "切断" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "証明書インポートのキャンセル", "text": "キャンセル" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "接続の有効化", "text": "接続" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "接続ファイルのインポート",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "接続のインポート" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "接続の編集" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "自動接続", "text": "自動接続" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "削除" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "名前の変更" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "認証情報のクリア" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "接続" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "ユーザーの認証" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "必要な方法でサインイン" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "ユーザー名とパスワードを保存する" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "サインイン" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "接続",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "ネットワーク",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "セキュリティ",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "接続の監視" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "お待ちください。接続を確立しています..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "お待ちください。接続の詳細を収集しています..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "XG Firewall 環境で Sophos Connect 用のリモート アクセス プロファイルを作成する方法は、次の情報を参照してください。" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Sophos Connect プロファイルの作成", "text": "Sophos Connect プロファイルの作成" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "証明書の認証情報のインポート" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "この接続の IKE 認証には、証明書と秘密鍵が必要です。  インポートする PKCS#12 ファイルを選択して、ファイルの暗号化に使用したパスワードを入力してください。" } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "パスワードの入力",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "PKCS#12 ファイルのインポート",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "PKCS#12 ファイルのインポート" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "インターネットアクセスがありません。お待ちください。インターネットアクセスが復元したら、再接続を試みます。" } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "発生日時" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "説明" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "イベントページのクリア", "text": "イベントのクリア" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited.All rights reserved." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "利用条件の詳細の表示",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "利用条件の詳細" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "バージョン" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Sophos Connect サービス" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "strongSwan サービス" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "トラブルシューティング" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "テクニカルサポート レポートの生成", "text": "テクニカルサポート レポートの生成" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Sophos Community ユーザーフォーラム (英語) を開く",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "ユーザーフォーラム" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "接続名" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "ゲートウェイ" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "リモート IKE ID" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "ローカル IKE ID" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "接続日時" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "ローカル IP" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "ゲートウェイ IP" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "仮想 IP アドレス" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "DNS サーバー" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "DNS サフィックス" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "リモートネットワーク" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "リモートネットワーク" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "受信バイト数" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "送信バイト数" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "受信パケット数" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "送信パケット数" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "アクティブな IPsec SA (セキュリティアソシエーション) はありません" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "暗号化アルゴリズムおよび鍵サイズ" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "整合性アルゴリズム" } ],
  [ SC_TID_MONITOR_PRF, {"text": "擬似乱数関数" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Diffie-Hellman グループ" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "次のリキー" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "認証中です..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "この名前の接続は既に存在します。続行すると、既存の接続は上書きされます。続行しますか？" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "この名前の接続は既に存在します。別の名前を選択してください" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "ユーザーの認証情報を消去しますか？" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "ファイルインポートのエラー" } ],
  [ SC_TID_DAY, {"text": "日" } ],
  [ SC_TID_DAYS, {"text": "日" } ],
  [ SC_TID_HOUR, {"text": "時間" } ],
  [ SC_TID_HOURS, {"text": "時間" } ],
  [ SC_TID_MINUTE, {"text": "分" } ],
  [ SC_TID_MINUTES, {"text": "分" } ],
  [ SC_TID_SECOND, {"text": "秒" } ],
  [ SC_TID_SECONDS, {"text": "秒" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "お待ちください。間もなく接続を再試行します" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "SSL VPN" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "圧縮" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "VPN の種類" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "暗号化アルゴリズム" } ],
  [ SC_TID_TRUE, {"text": "真" } ],
  [ SC_TID_FALSE, {"text": "偽" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "ポリシーの更新" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "現在の接続のポリシーを更新しますか？" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "ポリシーを更新しています" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "SSL プロビジョニングポリシー" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "接続してポリシーをダウンロードします" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "証明書のセキュリティ警告後、ユーザーは続行しました" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "証明書のセキュリティ警告後、ユーザーは停止しました" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "OpenVPN サービス" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "クレジットページを開く",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "オープンソースソフトウェアのクレジット" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "上の画像に表示される文字を入力してください",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "下の画像に表示される文字を入力してください",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "更新" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "接続がプライベートではありません" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "サーバーに進む (安全でない)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "サーバーの SSL 証明書のバイパス" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "サーバーのセキュリティ証明書は、使用しているコンピュータの OS によって信頼されていません。これは、設定が正しくないか、攻撃者が接続をインターセプトしたことが原因である可能性があります。" } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "攻撃者が情報 (例: パスワード、メッセージ、クレジットカード情報など) を盗もうとしている可能性があります。" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "SSO の再ログインの強制" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "VPN ポータルポートに有効な値を入力してください。" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "SSO が設定されていません。管理者に問い合わせてください。" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "ユーザー名とパスワード" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "ユーザー名" }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "パスワード" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "新しいトークンまたはワンタイムパスワード" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "または" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "シングルサインオン (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "シングルサインオン (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "VPN ポータルのポート" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "管理者が要求した場合にのみポートを編集してください" }],
];
