var labelArray_es_es = 
[
  [ SC_TID_PRODUCT_NAME, {"text": "Sophos Connect" } ],
  [ SC_TID_CONNECTIONS_TAB, {"elemId": "connectionsTab", "text": "Conexiones" } ],
  [ SC_TID_EVENTS_TAB, {"elemId": "eventsTab", "text": "Eventos" } ],
  [ SC_TID_APP_MENU, {"elemId": "ellipsisIcon", "title": "Menú",  } ],
  [ SC_TID_APP_MENU_IMPORT, {"elemId": "importFileLinkText", "text": "Importar conexión" } ],
  [ SC_TID_APP_MENU_LOG, {"elemId": "logMenuItemLInk", "text": "Abrir registro de VPN" } ],
  [ SC_TID_APP_MENU_HELP, {"elemId": "helpMILink", "text": "Ayuda" } ],
  [ SC_TID_APP_MENU_ABOUT, {"elemId": "aboutMIText", "text": "Acerca de" } ],
  [ SC_TID_APP_MENU_QUIT, {"elemId": "quitMIText", "text": "Salir" } ],
  [ SC_TID_STATUS_CANCEL_BTN, {"elemId": "connectBtn", "title": "Cancelar autenticación", "text": "Cancelar" } ],
  [ SC_TID_STATUS_DISCONNECT_BTN, {"elemId": "connectBtn", "title": "Desactivar conexión", "text": "Desconectar" } ],
  [ SC_TID_STATUS_CANCEL_IMPORT_CERT_BTN, {"elemId": "connectBtn", "title": "Cancelar la importación del certificado", "text": "Cancelar" } ],
  [ SC_TID_STATUS_CONNECT_BTN, {"elemId": "connectBtn", "title": "Activar conexión", "text": "Conectar" } ],
  [ SC_TID_IMPORT_BTN, {"elemId": "importBtn", "title": "Importar un archivo de conexión",  } ],
  [ SC_TID_IMPORT_BTN_TEXT, {"elemId": "importBtnText", "text": "Importar conexión" } ],
  [ SC_TID_EDIT_MENU_ICON, {"text": "Editar conexión" } ],
  [ SC_TID_EDIT_MENU_AUTO_CONNECT, {"elemId": "autoConnectMIT", "title": "Conexión automática", "text": "Conexión automática" } ],
  [ SC_TID_EDIT_MENU_DELETE, {"elemId": "deleteMIT", "text": "Eliminar" } ],
  [ SC_TID_EDIT_MENU_RENAME, {"elemId": "renameMIT", "text": "Cambiar nombre" } ],
  [ SC_TID_EDIT_MENU_CLEAR_CREDENTIALS, {"elemId": "clearCredentialsMIT", "text": "Borrar credenciales" } ],
  [ SC_TID_CONNECTIONS_PAGE_TITLE, {"elemId": "connectionsPageTitleText", "text": "Conexiones" } ],
  [ SC_TID_AUTH_PAGE_TITLE, {"elemId": "authPageTitle", "text": "Autenticar usuario" } ],
  [SC_TID_AUTH_PAGE_INTRO, { "elemId": "authPageIntroText", "text": "Iniciar sesión con el método preferido" } ],
  [ SC_TID_AUTH_PAGE_USER, {"elemId": "user", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_PASSWORD, {"elemId": "pass", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_OTP, {"elemId": "otp", "placeholder": "",  } ],
  [ SC_TID_AUTH_PAGE_SAVE_CREDENTIALS, {"elemId": "saveCredentialsLabel", "text": "Guardar nombre de usuario y contraseña" } ],
  [ SC_TID_AUTH_PAGE_SEND_BTN, {"elemId": "send", "text": "Conectarse" } ],
  [ SC_TID_MONITOR_CONNECTION_ICON, {"elemId": "connectionIcon", "title": "Conexión",  } ],
  [ SC_TID_MONITOR_NETWORKS_ICON, {"elemId": "networksIcon", "title": "Redes",  } ],
  [ SC_TID_MONITOR_SECURITY_ICON, {"elemId": "securityIcon", "title": "Seguridad",  } ],
  [ SC_TID_MONITOR_PAGE_TITLE, {"elemId": "monitorPageTitleText", "text": "Monitorizar conexión" } ],
  [ SC_TID_MONITOR_PAGE_CONNECTING, {"elemId": "connectingMsg", "text": "Espere mientras se establece la conexión..." } ],
  [ SC_TID_MONITOR_PAGE_POLLING, {"elemId": "pollingMsg", "text": "Espere mientras se recopilan los datos de la conexión..." } ],
  [ SC_TID_IMPORT_PAGE_TEXT, {"elemId": "importDetailsParaText", "text": "Para obtener instrucciones sobre cómo crear un perfil de acceso remoto para Sophos Connect en XG Firewall, consulte la siguiente información:" } ],
  [ SC_TID_IMPORT_PAGE_LINK, {"elemId": "importDetailsLink", "title": "Crear perfil de Sophos Connect", "text": "Crear perfil de Sophos Connect" } ],
  [ SC_TID_CERT_PAGE_TITLE, {"elemId": "certPageTitle", "text": "Importar credenciales de certificado" } ],
  [ SC_TID_CERT_PAGE_INTRO, {"elemId": "certPageIntroText", "text": "La autenticación de IKE de esta conexión requiere un certificado y una clave privada.  Seleccione un archivo PKCS#12 para importarlo e introduzca la contraseña que se utilizó para cifrar el archivo." } ],
  [ SC_TID_CERT_PAGE_PASSWORD, {"elemId": "pk12Password", "placeholder": "Introducir contraseña",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TITLE, {"elemId": "importCertBtn", "title": "Importar un archivo PKCS#12",  } ],
  [ SC_TID_IMPORT_CERT_BTN_TEXT, {"elemId": "importCertBtnText", "text": "Importar archivo PKCS#12" } ],
  [ SC_TID_OUTAGE_PAGE_TEXT, {"elemId": "outageDetailsText", "text": "No hay acceso a Internet. Espere. Intentaremos la conexión de nuevo cuando se restablezca el acceso a Internet." } ],
  [ SC_TID_EVENTS_PAGE_HDR_TS, {"elemId": "eventsHdrTS", "text": "Ocurrido" } ],
  [ SC_TID_EVENTS_PAGE_HDR_MSG, {"elemId": "eventsHdrMsg", "text": "Descripción" } ],
  [ SC_TID_CLEAR_EVENTS_BTN, {"elemId": "clearEventsBtn", "title": "Página Borrar eventos", "text": "Borrar eventos" } ],
  [ SC_TID_ABOUT_PAGE_COPYRIGHT, {"elemId": "copyrightText", "text": "Copyright 2019-2025 Sophos Limited. Todos los derechos reservados." } ],
  [ SC_TID_ABOUT_PAGE_LEGAL, {"elemId": "legal", "title": "Ver información legal",  } ],
  [ SC_TID_ABOUT_PAGE_LEGAL_LINK, {"elemId": "legalLink", "text": "Información legal" } ],
  [ SC_TID_ABOUT_PAGE_VERSIONS_HDR, {"elemId": "versionsHdr", "text": "Versión" } ],
  [ SC_TID_ABOUT_PAGE_SC_SERVICE, {"elemId": "sophosConnectText", "text": "Servicio Sophos Connect" } ],
  [ SC_TID_ABOUT_PAGE_STRONGSWAN, {"elemId": "strongSwanText", "text": "Servicio strongSwan" } ],
  [ SC_TID_ABOUT_PAGE_TROUBLESHOOTING, {"elemId": "troubleshootingHdr", "text": "Solución de problemas" } ],
  [ SC_TID_ABOUT_PAGE_TSR, {"elemId": "generateTSR", "title": "Generar informe de soporte técnico", "text": "Generar informe de soporte técnico" } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY, {"elemId": "community", "title": "Abrir foro de Sophos Community",  } ],
  [ SC_TID_ABOUT_PAGE_COMMUNITY_LINK, {"elemId": "communityLink", "text": "Foro de la comunidad" } ],
  [ SC_TID_MONITOR_CONNECTION_NAME, {"text": "Nombre de conexión" } ],
  [ SC_TID_MONITOR_GATEWAY, {"text": "Puerta de enlace" } ],
  [ SC_TID_MONITOR_REMOTE_ID, {"text": "ID de IKE remoto" } ],
  [ SC_TID_MONITOR_LOCAL_ID, {"text": "ID de IKE local" } ],
  [ SC_TID_MONITOR_CONNECTED, {"text": "Conectados" } ],
  [ SC_TID_MONITOR_LOCAL_IP, {"text": "IP local" } ],
  [ SC_TID_MONITOR_GATEWAY_IP, {"text": "IP de puerta de enlace" } ],
  [ SC_TID_MONITOR_VIRTUAL_IP, {"text": "Dirección IP virtual" } ],
  [ SC_TID_MONITOR_DNS_SERVERS, {"text": "Servidores DNS" } ],
  [ SC_TID_MONITOR_DNS_SUFFIXES, {"text": "Sufijos DNS" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORK, {"text": "Red remota" } ],
  [ SC_TID_MONITOR_REMOTE_NETWORKS, {"text": "Redes remotas" } ],
  [ SC_TID_MONITOR_BYTES_RECEIVED, {"text": "Bytes recibidos" } ],
  [ SC_TID_MONITOR_BYTES_TRANSMITTED, {"text": "Bytes transmitidos" } ],
  [ SC_TID_MONITOR_PACKETS_RECEIVED, {"text": "Paquetes recibidos" } ],
  [ SC_TID_MONITOR_PACKETS_TRANSMITTED, {"text": "Paquetes transmitidos" } ],
  [ SC_TID_MONITOR_NO_IPSEC_ACTIVE, {"text": "Ninguna SA (Asociación de seguridad) de IPsec activa" } ],
  [ SC_TID_MONITOR_IKE, {"text": "IKE" } ],
  [ SC_TID_MONITOR_ENCRYPTION_ALG, {"text": "Algoritmo de cifrado y tamaño de clave" } ],
  [ SC_TID_MONITOR_INTEGRETY_ALG, {"text": "Algoritmo de integridad" } ],
  [ SC_TID_MONITOR_PRF, {"text": "Función pseudoaleatoria" } ],
  [ SC_TID_MONITOR_DH_GROUP, {"text": "Grupo Diffie-Hellman" } ],
  [ SC_TID_MONITOR_NEXT_REKEY, {"text": "Próxima regeneración de clave" } ],
  [ SC_TID_MONITOR_IPSEC, {"text": "IPsec" } ],
  [ SC_TID_AUTHENTICATING, {"text": "Autenticando..." } ],
  [ SC_TID_OVERWRITE_CONFIRM, {"text": "Ya existe una conexión con este nombre. Si continúa, se sobrescribirá la conexión existente. ¿Continuar?" } ],
  [ SC_TID_CONNECTION_EXISTS_ALERT, {"text": "Existe una conexión con este nombre. Elija otra" } ],
  [ SC_TID_CLEAR_CREDENTIALS_CONFIRM, {"text": "¿Borrar las credenciales de usuario?" } ],
  [ SC_TID_FILE_IMPORT_ERROR, {"text": "Error al importar archivo" } ],
  [ SC_TID_DAY, {"text": "día" } ],
  [ SC_TID_DAYS, {"text": "días" } ],
  [ SC_TID_HOUR, {"text": "hora" } ],
  [ SC_TID_HOURS, {"text": "horas" } ],
  [ SC_TID_MINUTE, {"text": "minuto" } ],
  [ SC_TID_MINUTES, {"text": "minutos" } ],
  [ SC_TID_SECOND, {"text": "segundo" } ],
  [ SC_TID_SECONDS, {"text": "segundos" } ],
  [ SC_TID_RETRY_TEXT, {"elemId": "retryText", "text": "Espere. Volveremos a intentar la conexión en breve" } ],
  [ SC_TID_MONITOR_SSLVPN, {"text": "VPN SSL" } ],
  [ SC_TID_MONITOR_COMPRESSION, {"text": "Compresión" } ],
  [ SC_TID_MONITOR_VPN_TYPE, {"text": "Tipo de VPN" } ],
  [ SC_TID_MONITOR_SSL_ENCRYPTION_ALG, {"text": "Algoritmo de cifrado" } ],
  [ SC_TID_TRUE, {"text": "Verdadero" } ],
  [ SC_TID_FALSE, {"text": "Falso" } ],
  [ SC_TID_EDIT_MENU_UPDATE_CONNECTION, {"elemId": "updateConnectinMIT", "text": "Actualizar política" } ],
  [ SC_TID_UPDATE_CONNECTION_CONFIRM, {"text": "¿Actualizar la política para la conexión actual?" } ],
  [ SC_TID_UPDATE_CONNECTION_POLICY, {"text": "Actualizando política" } ],
  [ SC_TID_SSL_PROVISIONING_TYPE, {"text": "Política de aprovisionamiento SSL" } ],
  [ SC_TID_CONNECT_TO_DOWNLOAD, {"text": "Conectar para descargar política" } ],
  [ SC_TID_ACCEPTED_CERT_WARNING, {"text": "El usuario ha continuado después de la advertencia de seguridad del certificado" } ],
  [ SC_TID_REJECTED_CERT_WARNING, {"text": "El usuario se ha detenido después de la advertencia de seguridad del certificado" } ],
  [ SC_TID_ABOUT_PAGE_OPENVPN, {"elemId": "openVpnText", "text": "Servicio OpenVPN" } ],
  [ SC_TID_ABOUT_PAGE_CREDITS, {"elemId": "credits", "title": "Abrir página de créditos",  } ],
  [ SC_TID_ABOUT_PAGE_CREDITS_LINK, {"elemId": "attributionLink", "text": "Créditos del software de código abierto" } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA, {"elemId": "captcha", "placeholder": "Introduzca los caracteres mostrados en la imagen de arriba",  } ],
  [ SC_TID_AUTH_PAGE_CAPTCHA_IMAGE, {"elemId": "imgCaptcha", "title": "Introduzca los caracteres mostrados en la imagen de abajo",  } ],
  [ SC_TID_AUTH_PAGE_REFRESH_CAPTCHA_BTN, {"elemId": "refreshCaptcha", "text": "Actualizar" } ],
  [ SC_TID_NOT_PRIVATE_CONNECTION, {"text": "La conexión no es privada" } ],
  [ SC_TID_PROCEED_TO_CONNNECT, {"elemId": "proceed", "text": "Continuar en el servidor (no seguro)" } ],
  [ SC_TID_BYPASS_SSL_PAGE_TITLE, {"elemId": "byPassSslPageTitleText", "text": "Omitir certificado SSL del servidor" } ],
  [ SC_TID_SSL_CONNECTION_ERROR_ADV, {"elemId": "sslErrAdvText", "text": "El certificado de seguridad del servidor no es de confianza para el sistema operativo de su ordenador. Esto puede deberse a una configuración incorrecta o a que un atacante ha interceptado su conexión." } ],
  [SC_TID_SSL_CONNECTION_ERROR, { "elemId": "sslErrText", "text": "Es posible que algún atacante esté intentando robarle información (por ejemplo, contraseñas, mensajes o datos de tarjetas de crédito)" }],
  [SC_TID_APP_MENU_FORCE_SSO_RELOGON, { "elemId": "forceSSORelogonMIText", "text": "Forzar reconexión con SSO" }],
  [SC_TID_TOOLTIP_ENTER_VALID_PORT_VALUE, { "elemId": "sso-button-tooltip", "text": "Introduzca un valor válido para el puerto del portal VPN" }],
  [SC_TID_TOOLTIP_SSO_DETAILS_MISSING_CONNECT_TO_ADMIN, { "elemId": "sso-button-tooltip", "text": "El SSO no está configurado. Póngase en contacto con su administrador" }],
  [SC_TID_USER_AND_PASS_SIGN_IN_TITLE, { "elemId": "user-and-pass-sign-in-title", "text": "Nombre de usuario y contraseña" }],
  [SC_TID_USER_NAME_TITLE, { "elemId": "user-name-title", "text": "Nombre de usuario " }],
  [SC_TID_PASSWORD_TITLE, { "elemId": "password-title", "text": "Contraseña" }],
  [SC_TID_OTP_TITLE, { "elemId": "otp-title", "text": "Nuevo token o contraseña de un solo uso" }],
  [SC_TID_SIGN_IN_OPTIONS_SEPARATOR_OR_TITLE, { "elemId": "sign-in-options-separator-OR-title", "text": "O" }],
  [SC_TID_SIGN_IN_VIA_SSO_TITLE, { "elemId": "sign-in-via-sso-title", "text": "Inicio de sesión único (SSO)" }],
  [SC_TID_SSO_BUTTON, { "elemId": "sso-button", "text": "Inicio de sesión único (SSO)" }],
  [SC_TID_VPN_PORTAL_PORT_BUTTON_LABEL_TITLE, { "elemId": "vpn-portal-port-button-label-title", "text": "Puerto del portal VPN" }],
  [SC_TID_VPN_PORTAL_PORT_WARNING, { "elemId": "vpn-portal-port-warning", "text": "Solo edite el puerto si su administrador lo solicita" }], ,
 ];
