var statusMsgArray_de_de = 
[
  [SC_SID_RESOLVE_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "DNS-Auflösung fehlgeschlagen für Gateway: %%1%%" }],
  [SC_SID_NO_INTERNET_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Keine Internetverbindung" }],
  [SC_SID_PING_SEND_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Ping konnte nicht gesendet werden" }],
  [SC_SID_PING_RECV_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Ping konnte nicht empfangen werden" }],
  [SC_SID_SOCK_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Socket konnte nicht erstellt werden" }],
  [SC_SID_SOCK_ADDR_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Es fehlen Adressinformationen" }],
  [SC_SID_TIMEOUT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Zeitüberschreitung beim Warten auf Serverantwort" }],
  [SC_SID_ERRORED_OUT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Fehler beim Warten auf Serverantwort" }],
  [SC_SID_INVALID_P2_ID, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Phase 2 ID Proposal ungültig" }],
  [SC_SID_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Meldung NO_PROPOSAL_CHOSEN erhalten von Gateway: %%1%%" }],
  [SC_SID_CHILD_SA_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Child SA (Security Association) konnte nicht hergestellt werden" }],
  [SC_SID_ZIP_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Bericht für den Technischen Support konnte nicht erstellt werden" }],
  [SC_SID_CONN_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Verbindung konnte nicht importiert werden" }],
  [SC_SID_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Das Zertifikat konnte nicht importiert werden" }],
  [SC_SID_CERT_IMPORT_REQUIRED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Zertifikatimport ist erforderlich" }],
  [SC_SID_CONN_LIST_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Liste der Verbindungen konnte nicht abgerufen werden" }],
  [SC_SID_NEED_AUTH_ERR, { "args": 0, "state": "normal", "targets": 1, "title": "Authentifizierung erforderlich", "msg": "Geben Sie die Benutzer-Anmeldeinformationen ein" }],
  [SC_SID_CONN_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Verbindung konnte nicht geladen werden" }],
  [SC_SID_CERT_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Zertifikat konnte nicht geladen werden" }],
  [SC_SID_SWAN_CMD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Befehl konnte nicht an IPsec-Dienst gesendet werden" }],
  [SC_SID_SA_TERMINATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "SA (Security Association) konnte nicht beendet werden" }],
  [SC_SID_SA_UNLOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "SA (Security Association) konnte nicht entfernt werden" }],
  [SC_SID_CONN_NOT_ENABLED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Verbindung nicht aktiviert" }],
  [SC_SID_INVALID_REQUEST, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Ungültige Anforderung" }],
  [SC_SID_CONN_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Verbindung nicht gefunden" }],
  [SC_SID_CONN_FORMAT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Die Verbindung konnte nicht hinzugefügt werden – ungültige Konfiguration" }],
  [SC_SID_CONN_PARSE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Die Verbindung konnte nicht geparst werden – unbekanntes Format" }],
  [SC_SID_CONN_CONFIG_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Die Verbindung konnte nicht hinzugefügt werden – ungültiges Format" }],
  [SC_SID_USER_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Benutzerzertifikat konnte nicht importiert werden" }],
  [SC_SID_CA_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "CA-Zertifikat konnte nicht importiert werden" }],
  [SC_SID_KEY_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Privater Schlüssel konnte nicht importiert werden" }],
  [SC_SID_SVC_STOPPED_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "VPN-Dienst wurde angehalten" }],
  [SC_SID_IKE_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "IKE-Meldung NO_PROPOSAL_CHOSEN erhalten von Gateway: %%1%%" }],
  [SC_SID_INTERNAL_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Es ist ein interner Fehler aufgetreten" }],
  [SC_SID_IKE_SEND_ERR, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_PSK_MISMATCH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falscher PSK" }],
  [SC_SID_IKE_NO_RESPONSE_ERR, { "args": 1, "state": "error", "targets": 3, "title": "Verbindung fehlgeschlagen", "msg": "Keine Antwort von Gateway: %%1%%" }],
  [SC_SID_SENDING_DPD_REQUEST, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RECEIVED_DPD_ACK, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SENDING_IKE_DELETE, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_AUTH_CANCELLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Benutzerauthentifizierung abgebrochen" }],
  [SC_SID_ERR_FILE_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Die angegebene Datei wurde nicht gefunden" }],
  [SC_SID_ERR_CONN_EXISTS, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Verbindung %%1%% existiert bereits" }],
  [SC_SID_ERR_TELEM_SEND, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_SVC_BUSY, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_HTTP_SEND, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_VPN_UNSTABLE, { "args": 1, "state": "warning", "targets": 7, "title": "Verbindung instabil", "msg": "Verbindung %%1%% ist instabil geworden" }],
  [SC_SID_DISABLED_UPON_WAKEUP, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% nach Aufwachen aus dem Energiesparmodus deaktiviert" }],
  [SC_SID_DISABLED_BY_CLI, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% wurde über die Befehlszeile deaktiviert" }],
  [SC_SID_DISABLED_BY_GATEWAY, { "args": 1, "state": "warning", "targets": 3, "title": "Verbindung deaktiviert", "msg": "Verbindung wurde vom Gateway deaktiviert: %%1%%" }],
  [SC_SID_SA_NO_LONGER_EXISTS, { "args": 1, "state": "error", "targets": 3, "title": "Verbindung deaktiviert", "msg": "Verbindung %%1%% wurde deaktiviert" }],
  [SC_SID_DISABLED_INTERFACE_DOWN, { "args": 1, "state": "warning", "targets": 3, "title": "Verbindung deaktiviert", "msg": "Die Verbindung %%1%% wurde deaktiviert. Netzwerkverbindung verloren gegangen" }],
  [SC_SID_DPD_TIMEOUT, { "args": 1, "state": "warning", "targets": 7, "title": "", "msg": "Verbindung verloren gegangen zu Gateway: %%1%%" }],
  [SC_SID_IKE_FAILURE, { "args": 0, "state": "warning", "targets": 3, "title": "Verbindung schlägt möglicherweise fehl", "msg": "Der UDP-Port für IKE ist offenbar blockiert" }],
  [SC_SID_NO_INTERNET, { "args": 0, "state": "warning", "targets": 3, "title": "Netzwerk nicht verfügbar", "msg": "Keine Internetverbindung verfügbar" }],
  [SC_SID_ESTABLISHING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% wird hergestellt" }],
  [SC_SID_CONNECTED, { "args": 1, "state": "connected", "targets": 7, "title": "Verbindung hergestellt", "msg": "Verbindung %%1%% hergestellt" }],
  [SC_SID_CONN_NOT_RESTARTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Im internen Netzwerk – Verbindung %%1%% ist nicht erforderlich" }],
  [SC_SID_INITIATING_AUTOCONNECT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Automatisches Verbinden für %%1%% wird gestartet" }],
  [SC_SID_AUTOIMPORT_SUCCESS, { "args": 2, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% wurde automatisch aus Datei %%2%% importiert" }],
  [SC_SID_AUTOIMPORT_FAILURE, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Automatischer Import der Datei %%1%% fehlgeschlagen" }],
  [SC_SID_CONN_LIST_CHANGED, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SERVICE_ENABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Der VPN-Dienst wurde aktiviert" }],
  [SC_SID_SERVICE_UNAVAILABLE, { "args": 0, "state": "error", "targets": 3, "title": "Dienst nicht verfügbar", "msg": "Stellen Sie sicher, dass der VPN-Dienst ausgeführt wird" }],
  [SC_SID_ALREADY_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Die angeforderte Aktion wird bereits ausgeführt" }],
  [SC_SID_SWAN_CONNECT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Es konnte keine Verbindung zu strongSwan hergestellt werden" }],
  [SC_SID_NO_AUTO_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Automatisches Verbinden ist nicht verfügbar" }],
  [SC_SID_INITALIZING, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Initialisierung" }],
  [SC_SID_LAST_CONNECTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Zuletzt verbunden %%1%%" }],
  [SC_SID_NEVER_CONNECTED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Noch nie verbunden" }],
  [SC_SID_CONNECTED_TODAY, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Heute verbunden %%1%%" }],
  [SC_SID_CONNECTING, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "%%1%% wird mit gespeicherten Anmeldeinformationen verbunden" }],
  [SC_SID_CANCELLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Abgebrochener Verbindungsversuch für %%1%%" }],
  [SC_SID_DISABLING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% wird deaktiviert" }],
  [SC_SID_DISABLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% deaktiviert" }],
  [SC_SID_CONNECTION_ALREADY_DISABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung ist bereits deaktiviert" }],
  [SC_SID_REMOVING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% wird entfernt" }],
  [SC_SID_CONNECTION_ADDED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% hinzugefügt" }],
  [SC_SID_CONNECTION_REMOVED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindung %%1%% entfernt" }],
  [SC_SID_REMOVE_CONNECTION_CONFIRM, { "args": 1, "state": "warning", "targets": 2, "title": "", "msg": "Diese Verbindung entfernen: %%1%%?" }],
  [SC_SID_CERTIFICATE_IMPORTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Zertifikat importiert für %%1%%" }],
  [SC_SID_ADDING_CONNECTION_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindungsdatei %%1%% wird hinzugefügt" }],
  [SC_SID_ADDING_CERTIFICATE_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Zertifikatdatei %%1%% wird hinzugefügt" }],
  [SC_SID_PKCS12_ALERT, { "args": 0, "state": "warning", "targets": 2, "title": "Falsches Dateiformat", "msg": "Wählen Sie eine PKCS#12-Datei für den Import aus" }],
  [SC_SID_CERTIFICATE_IMPORT_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Zertifikatimport fehlgeschlagen: %%1%%" }],
  [SC_SID_SC_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Sophos-Connect-Version: %%1%%" }],
  [SC_SID_SS_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "strongSwan-Version: %%1%%" }],
  [SC_SID_SS_VERSION_UNAVAILABLE, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Der strongSwan-Dienst ist nicht verfügbar" }],
  [SC_SID_SYSTEM_ERR_MSG, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "Fehler – Code: %%1%% Nachricht: %%2%%" }],
  [SC_SID_AUTH_SUCCEEDED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Authentifizierung erfolgreich" }],
  [SC_SID_CLEARED_CREDENTIALS, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Gespeicherte Benutzer-Anmeldeinformationen für Verbindung %%1%% gelöscht" }],
  [SC_SID_CLEAR_CREDENTIALS_ERR, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Fehler beim Löschen gespeicherter Benutzer-Anmeldeinformationen für Verbindung %%1%%" }],
  [SC_SID_MISSING_RESPONSE, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Keine Antwort" }],
  [SC_SID_MISSING_CONFIG_DATA, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Keine Konfigurationsdaten" }],
  [SC_SID_EDITED_CONNECTION_NAME, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindungsname bearbeitet [%%1%%]" }],
  [SC_SID_CANCELLED_EDIT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Verbindungsname bearbeitet – Bearbeitung abgebrochen [%%1%%]" }],
  [SC_SID_APP_QUIT_CONNFIRM, { "args": 1, "state": "normal", "targets": 2, "title": "", "msg": "Wenn Sie fortfahren, wird die Verbindung %%1%% getrennt. Beenden?" }],
  [SC_SID_NO_CONNECTIONS, { "args": 0, "state": "normal", "targets": 2, "title": "Sophos Connect", "msg": "Noch keine Verbindungen vorhanden. Eine Verbindung importieren" }],
  [SC_SID_IMPORT_FILE_EMPTY_ERR, { "args": 1, "state": "error", "targets": 2, "title": "Fehler beim Importieren der Datei", "msg": "Datei %%1%% kann nicht importiert werden, weil sie leer ist" }],
  [SC_SID_IMPORT_FILE_SIZE_ERR, { "args": 1, "state": "error", "targets": 2, "title": "Fehler beim Importieren der Datei", "msg": "Verbindungs-Importdatei %%1%% ist zu groß" }],
  [SC_SID_ON_NETWORK, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Im internen Netzwerk. Automatisches Verbinden nicht erforderlich" }],
  [SC_SID_AUTH_FAILED, { "args": 0, "state": "warning", "targets": 1, "title": "Authentifizierung fehlgeschlagen", "msg": "Benutzerauthentifizierung fehlgeschlagen. Bitte versuchen Sie es erneut" }],
  [SC_SID_ADD_ROUTE_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Route %%1%% konnte nicht hinzugefügt werden, daher konnte Phase 2 nicht abgeschlossen werden" }],
  [SC_SID_INVALID_SERVER_CERT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Serverzertifikat konnte nicht validiert werden" }],
  [SC_SID_IDIR_MISMATCH_ERR, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "Falsche ID. %%1%% erwartet, %%2%% erhalten" }],
  [SC_SID_NEED_OTP, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Einmalkennwort erforderlich" }],
  [SC_SID_NOT_PERMITTED_ERR, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "Die angeforderte Aktion ist derzeit nicht erlaubt" }],
  [SC_SID_SSL_VPN_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "SSL-VPN-Fehler: %%1%%" }],
  [SC_SID_FILE_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Es konnte keine temporäre Datei erstellt werden" }],
  [SC_SID_SRV_DOWN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "OpenVPN-Dienst nicht verfügbar" }],
  [SC_SID_PIPE_WRITE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Fehler beim Schreiben in die Pipe" }],
  [SC_SID_MGMT_SOCK_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Management-Port ist nicht verfügbar" }],
  [SC_SID_UNTRUSTED_SERVER_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Verbindung zum nicht vertrauenswürdigen Server nicht möglich: %%1%%" }],
  [SC_SID_SERVER_CERT_CONFIRM, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Server-Zertifikat kann nicht verifiziert werden: %%1%%. Möchten Sie fortsetzen?" }],
  [SC_SID_DUPLICATE_CONNECTION, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Die Importdatei enthält eine doppelte Verbindung: %%1%%" }],
  [SC_SID_POLICY_GATEWAY_CONNECT_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Es kann keine Verbindung zum Richtlinien-Gateway hergestellt werden: %%1%%" }],
  [SC_SID_NO_SSLVPN_POLICY_ERR, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "Für diesen Benutzer ist keine SSL-VPN-Richtlinie definiert: %%1%%" }],
  [SC_SID_BAD_COMPRESSION_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Fehler wegen unterschiedlicher Komprimierung. Verbindung wird erneut hergestellt" }],
  [SC_SID_POLICY_UPLOAD_MSG, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Fehler wegen Richtlinienabweichung. Die Richtlinie wird heruntergeladen und es wird erneut versucht, die Verbindung herzustellen" }],
  [SC_SID_POLICY_IMPORT_MSG, { "args": 0, "state": "error", "targets": 3, "title": "", "msg": "Fehler wegen Richtlinienabweichung. Importieren Sie eine neue Richtlinie für diese Verbindung" }],
  [SC_SID_SSL_CONNECTION_RESET, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "Information über das Zurücksetzen der Verbindung von Gateway: %%1%% erhalten" }],
  [SC_SID_NAME_LENGTH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Verbindungsname darf nicht länger als 60 Zeichen sein" }],
  [SC_SID_OPENVPN_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "OpenVPN-Version: %%1%%" }],
  [SC_SID_TRYING_TO_CONNECT, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Verbindungsversuch mit %%1%%" }],
  [SC_SID_GEN_1_ARG, { "args": 1, "state": "normal", "targets": 1, "title": "One argument", "msg": "A message with %%1%% required argument" }],
  [SC_SID_GEN_2_ARG, { "args": 2, "state": "warning", "targets": 5, "title": "Two arguments", "msg": "A message with %%1%% and %%2%% required arguments" }],
  [SC_SID_GEN_3_ARG, { "args": 3, "state": "error", "targets": 3, "title": "Three arguments", "msg": "A message with %%1%%, %%2%%, and %%3%% required arguments" }],
  [SC_SID_TEST_SYSTEM, { "args": 0, "state": "normal", "targets": 4, "title": "System", "msg": "A system message" }],
  [SC_SID_SSO_AUTH_SUCCESS, { "args": 1, "state": "normal", "targets": 1, "title": "SSO Auth", "msg": "SSO-Authentifizierung für Gateway %%1%% erfolgreich" }],
  [SC_SID_SSO_AUTH_WV2_SETUP_ERROR, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO-Authentifizierung fehlgeschlagen. Die WebView2-Runtime ist nicht vorhanden. Bitte installieren Sie diese, um fortzufahren." }],
  [SC_SID_SSO_AUTH_FQDN_NAVIGATION_FAILED, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO-Authentifizierung für Gateway %%1%% konnte nicht abgeschlossen werden" }],
  [SC_SID_SSO_AUTH_USER_EMBEDDED_BROWSER, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO-Authentifizierung für Gateway %%1%% nicht erfolgreich, weil der Benutzer das Dialogfeld geschlossen hat" }],
  [SC_SID_SSO_AUTH_INVALID_AUTH_RESPONSE, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO-Authentifizierung für Gateway %%1%% nicht erfolgreich, weil Pflichtfelder in der Antwort fehlen" }],
  [SC_SID_SSO_AUTH_TIMEOUT, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO-Authentifizierung für Gateway %%1%% wegen Zeitüberschreitung nicht erfolgreich" }],
  [SC_SID_SSO_CLEAR_COOKIE_SUCCESS, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "SSO-Cookie gelöscht" }],
  [SC_SID_SSO_CLEAR_COOKIE_FAILED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "SSO-Cookie konnte nicht gelöscht werden" }],
  [SC_SID_SSO_COOKIE_NOTEXIST, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Kein SSO-Cookie gefunden" }],
  [SC_SID_SSO_TRIGGER_AUTH, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_FORCE_SSO_RE_LOGIN_CONFIRM_MSG, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "Erfordert SSO-Anmeldung bei der nächsten Verbindung" }],
  [SC_SID_SSO_NOT_ENABLED_PROV_GW, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO ist für das Bereitstellungs-Gateway %%1%% nicht aktiviert" }],
  [SC_SID_SSO_GATEWAY_UNREACHABLE, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO-Gateway %%1%% nicht erreichbar" }],
  [SC_SID_SSO_CERTIFICATE_REVOKED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO-Authentifizierung für Gateway %%1%% fehlgeschlagen, weil das Zertifikat widerrufen wurde" }],
  [SC_SID_SSO_CERTIFICATE_EXPIRED, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO-Authentifizierung für Gateway %%1%% fehlgeschlagen, weil das Zertifikat abgelaufen ist" }],
  [SC_SID_SSO_NO_REACHABLE_ENABLED_PROV_GW, {"args": 0, "state": "error", "targets": 1, "title": "SSO Auth", "msg": "Es ist kein Bereitstellungs-Gateway mit SSO-Authentifizierung verfügbar" }],
  [SC_SID_SSO_TRIGGER_CONN, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_GATEWAY_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_SSO_AUTH_SERVICE_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
];