var statusMsgArray_zh_cn = 
[
  [SC_SID_RESOLVE_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "此网关 DNS 解析失败： %%1%%" }],
  [SC_SID_NO_INTERNET_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "无因特网联机" }],
  [SC_SID_PING_SEND_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "传送 ping 失败" }],
  [SC_SID_PING_RECV_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接收 ping 失败" }],
  [SC_SID_SOCK_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "建立套接字失败" }],
  [SC_SID_SOCK_ADDR_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "缺少地址信息" }],
  [SC_SID_TIMEOUT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "等待服务器回应超时" }],
  [SC_SID_ERRORED_OUT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "等待服务器回应错误" }],
  [SC_SID_INVALID_P2_ID, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "无效的阶段 2 ID 提案" }],
  [SC_SID_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "已收到此网关的 NO_PROPOSAL_CHOSEN 通知： %%1%%" }],
  [SC_SID_CHILD_SA_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "建立子 SA（安全性关联）失败" }],
  [SC_SID_ZIP_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "建立技术支持报告失败" }],
  [SC_SID_CONN_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "导入连接失败" }],
  [SC_SID_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "导入证书失败" }],
  [SC_SID_CERT_IMPORT_REQUIRED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "必须导入证书" }],
  [SC_SID_CONN_LIST_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "取得连接清单失败" }],
  [SC_SID_NEED_AUTH_ERR, { "args": 0, "state": "normal", "targets": 1, "title": "需要认证", "msg": "请输入使用者认证" }],
  [SC_SID_CONN_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "加载连接失败" }],
  [SC_SID_CERT_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "加载凭证失败" }],
  [SC_SID_SWAN_CMD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "传送命令至 IPsec 服务失败" }],
  [SC_SID_SA_TERMINATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "终止子 SA（安全性关联）失败" }],
  [SC_SID_SA_UNLOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "解除加载 SA（安全性关联）失败" }],
  [SC_SID_CONN_NOT_ENABLED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "连接未启用" }],
  [SC_SID_INVALID_REQUEST, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "请求无效" }],
  [SC_SID_CONN_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "找不到连接" }],
  [SC_SID_CONN_FORMAT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "无法新增连接 - 无效的配置" }],
  [SC_SID_CONN_PARSE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "无法解析连接 - 未知的格式" }],
  [SC_SID_CONN_CONFIG_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "无法新增连接 - 无效的格式" }],
  [SC_SID_USER_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "导入用户证书失败" }],
  [SC_SID_CA_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "导入 CA 证书失败" }],
  [SC_SID_KEY_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "导入私钥失败" }],
  [SC_SID_SVC_STOPPED_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "VPN 服务已停止" }],
  [SC_SID_IKE_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "已收到此网关的 IKE NO_PROPOSAL_CHOSEN 通知： %%1%%" }],
  [SC_SID_INTERNAL_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "发生内部错误" }],
  [SC_SID_IKE_SEND_ERR, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_PSK_MISMATCH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "PSK 不正确" }],
  [SC_SID_IKE_NO_RESPONSE_ERR, { "args": 1, "state": "error", "targets": 3, "title": "联机失败", "msg": "此网关无回应： %%1%%" }],
  [SC_SID_SENDING_DPD_REQUEST, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RECEIVED_DPD_ACK, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SENDING_IKE_DELETE, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_AUTH_CANCELLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "使用者验证已取消" }],
  [SC_SID_ERR_FILE_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "找不到指定的文件" }],
  [SC_SID_ERR_CONN_EXISTS, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "连接 %%1%% 已存在" }],
  [SC_SID_ERR_TELEM_SEND, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_SVC_BUSY, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_HTTP_SEND, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_VPN_UNSTABLE, { "args": 1, "state": "warning", "targets": 7, "title": "连接不稳定", "msg": "连接 %%1%% 已变为不稳定" }],
  [SC_SID_DISABLED_UPON_WAKEUP, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "从休眠中唤醒后，连接 %%1%% 已停用" }],
  [SC_SID_DISABLED_BY_CLI, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "连接 %%1%% 已透过命令行接口停用" }],
  [SC_SID_DISABLED_BY_GATEWAY, { "args": 1, "state": "warning", "targets": 3, "title": "连接已停用", "msg": "连接 已停用：%%1%%" }],
  [SC_SID_SA_NO_LONGER_EXISTS, { "args": 1, "state": "error", "targets": 3, "title": "连接已停用", "msg": "连接 %%1%% 已停用" }],
  [SC_SID_DISABLED_INTERFACE_DOWN, { "args": 1, "state": "warning", "targets": 3, "title": "连接已停用", "msg": "连接 %%1%% 已停用。失去网络联机" }],
  [SC_SID_DPD_TIMEOUT, { "args": 1, "state": "warning", "targets": 7, "title": "", "msg": "此网关已失去连接： %%1%%" }],
  [SC_SID_IKE_FAILURE, { "args": 0, "state": "warning", "targets": 3, "title": "联机可能失败", "msg": "IKE UDP 埠似乎遭到拦截" }],
  [SC_SID_NO_INTERNET, { "args": 0, "state": "warning", "targets": 3, "title": "网络无法使用", "msg": "无可用的因特网联机" }],
  [SC_SID_ESTABLISHING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "正在建立连接 %%1%%" }],
  [SC_SID_CONNECTED, { "args": 1, "state": "connected", "targets": 7, "title": "连接已建立", "msg": "已建立连接 %%1%%" }],
  [SC_SID_CONN_NOT_RESTARTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "在内部网络上 - 不需要连接 %%1%%" }],
  [SC_SID_INITIATING_AUTOCONNECT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "开始自动联机 %%1%%" }],
  [SC_SID_AUTOIMPORT_SUCCESS, { "args": 2, "state": "normal", "targets": 1, "title": "", "msg": "连接 %%1%% 已从文件 %%2%% 自动导入" }],
  [SC_SID_AUTOIMPORT_FAILURE, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "自动导入文件 %%1%% 失败" }],
  [SC_SID_CONN_LIST_CHANGED, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SERVICE_ENABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "VPN 服务已启用" }],
  [SC_SID_SERVICE_UNAVAILABLE, { "args": 0, "state": "error", "targets": 3, "title": "服务无法使用", "msg": "请确认 VPN 服务正在执行" }],
  [SC_SID_ALREADY_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "请求的动作已在进行中" }],
  [SC_SID_SWAN_CONNECT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "连接至 strongSwan 失败" }],
  [SC_SID_NO_AUTO_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "自动联机无法使用" }],
  [SC_SID_INITALIZING, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "初始化" }],
  [SC_SID_LAST_CONNECTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "最后一次连接 %%1%%" }],
  [SC_SID_NEVER_CONNECTED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "从未连接" }],
  [SC_SID_CONNECTED_TODAY, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "今日连接 %%1%%" }],
  [SC_SID_CONNECTING, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "正在使用已存认证连接 %%1%%" }],
  [SC_SID_CANCELLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已取消 %%1%% 的连接尝试" }],
  [SC_SID_DISABLING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "正在停用连接 %%1%%" }],
  [SC_SID_DISABLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已停用连接 %%1%%" }],
  [SC_SID_CONNECTION_ALREADY_DISABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "连接已停用" }],
  [SC_SID_REMOVING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "正在移除连接 %%1%%" }],
  [SC_SID_CONNECTION_ADDED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已新增连接 %%1%%" }],
  [SC_SID_CONNECTION_REMOVED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已移除连接 %%1%%" }],
  [SC_SID_REMOVE_CONNECTION_CONFIRM, { "args": 1, "state": "warning", "targets": 2, "title": "", "msg": "移除此连接：%%1%%?" }],
  [SC_SID_CERTIFICATE_IMPORTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已为 %%1%% 导入证书" }],
  [SC_SID_ADDING_CONNECTION_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "正在新增连接文件 %%1%%" }],
  [SC_SID_ADDING_CERTIFICATE_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "正在新增证书文件 %%1%%" }],
  [SC_SID_PKCS12_ALERT, { "args": 0, "state": "warning", "targets": 2, "title": "文件格式不正确", "msg": "请选择要导入的 PKCS#12 文件" }],
  [SC_SID_CERTIFICATE_IMPORT_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "证书导入失败： %%1%%" }],
  [SC_SID_SC_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Sophos Connect 版本： %%1%%" }],
  [SC_SID_SS_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "strongSwan 版本： %%1%%" }],
  [SC_SID_SS_VERSION_UNAVAILABLE, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "strongSwan 服务无法使用" }],
  [SC_SID_SYSTEM_ERR_MSG, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "错误 - 代码：%%1%% 讯息： %%2%%" }],
  [SC_SID_AUTH_SUCCEEDED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "验证成功" }],
  [SC_SID_CLEARED_CREDENTIALS, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已清除连接 %%1%% 已存的使用者认证" }],
  [SC_SID_CLEAR_CREDENTIALS_ERR, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "清除连接 %%1%% 已存的使用者认证出错" }],
  [SC_SID_MISSING_RESPONSE, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "缺少回应" }],
  [SC_SID_MISSING_CONFIG_DATA, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "缺少配置数据" }],
  [SC_SID_EDITED_CONNECTION_NAME, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已编辑连接名称 [%%1%%]" }],
  [SC_SID_CANCELLED_EDIT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "已编辑连接名称 - 已取消编辑 [%%1%%]" }],
  [SC_SID_APP_QUIT_CONNFIRM, { "args": 1, "state": "normal", "targets": 2, "title": "", "msg": "若您继续，连接 %%1%% 将会断开。要退出吗？" }],
  [SC_SID_NO_CONNECTIONS, { "args": 0, "state": "normal", "targets": 2, "title": "Sophos Connect", "msg": "还没有连接。导入连接" }],
  [SC_SID_IMPORT_FILE_EMPTY_ERR, { "args": 1, "state": "error", "targets": 2, "title": "文件导入错误", "msg": "文件 %%1%% 无法导入，因为是空的" }],
  [SC_SID_IMPORT_FILE_SIZE_ERR, { "args": 1, "state": "error", "targets": 2, "title": "文件导入错误", "msg": "文件 %%1%% 超过连接文件汇入大小上限" }],
  [SC_SID_ON_NETWORK, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "在内部网络上。不需要自动连接" }],
  [SC_SID_AUTH_FAILED, { "args": 0, "state": "warning", "targets": 1, "title": "身份验证失败", "msg": "使用者验证失败。请重试" }],
  [SC_SID_ADD_ROUTE_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "新增路由 %%1%% 失败导致阶段 2 无法完成" }],
  [SC_SID_INVALID_SERVER_CERT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "验证服务器证书失败" }],
  [SC_SID_IDIR_MISMATCH_ERR, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "ID 不匹配。预期为 %%1%% 但结果为 %%2%%" }],
  [SC_SID_NEED_OTP, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "需要一次性密码" }],
  [SC_SID_NOT_PERMITTED_ERR, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "此时不允许执行请求的动作" }],
  [SC_SID_SSL_VPN_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "SSL VPN 错误：%%1%%" }],
  [SC_SID_FILE_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "创建临时文件失败" }],
  [SC_SID_SRV_DOWN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "OpenVPN 服务不可用" }],
  [SC_SID_PIPE_WRITE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "写入管道失败" }],
  [SC_SID_MGMT_SOCK_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "管理端口不可用" }],
  [SC_SID_UNTRUSTED_SERVER_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "无法连接到不受信任的服务器：%%1%%" }],
  [SC_SID_SERVER_CERT_CONFIRM, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "服务器证书无法验证：%%1%%.你确定要继续？" }],
  [SC_SID_DUPLICATE_CONNECTION, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "导入文件包含重复连接：%%1%%" }],
  [SC_SID_POLICY_GATEWAY_CONNECT_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "无法连接到策略网关：%%1%%" }],
  [SC_SID_NO_SSLVPN_POLICY_ERR, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "没有为此用户定义 SSL VPN 策略：%%1%%" }],
  [SC_SID_BAD_COMPRESSION_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "压缩不匹配错误。将重新尝试连接" }],
  [SC_SID_POLICY_UPLOAD_MSG, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "策略不匹配错误。将下载策略并重新尝试连接" }],
  [SC_SID_POLICY_IMPORT_MSG, { "args": 0, "state": "error", "targets": 3, "title": "", "msg": "策略不匹配错误。为此连接导入新策略" }],
  [SC_SID_SSL_CONNECTION_RESET, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "从网关收到连接重置：%%1%%" }],
  [SC_SID_NAME_LENGTH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "连接名称不能超过 60 个字符" }],
  [SC_SID_OPENVPN_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "OpenVPN 版本：%%1%%" }],
  [SC_SID_TRYING_TO_CONNECT, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "尝试连接到 %%1%%" }],
  [SC_SID_GEN_1_ARG, { "args": 1, "state": "normal", "targets": 1, "title": "One argument", "msg": "A message with %%1%% required argument" }],
  [SC_SID_GEN_2_ARG, { "args": 2, "state": "warning", "targets": 5, "title": "Two arguments", "msg": "A message with %%1%% and %%2%% required arguments" }],
  [SC_SID_GEN_3_ARG, { "args": 3, "state": "error", "targets": 3, "title": "Three arguments", "msg": "A message with %%1%%, %%2%%, and %%3%% required arguments" }],
  [SC_SID_TEST_SYSTEM, { "args": 0, "state": "normal", "targets": 4, "title": "System", "msg": "A system message" }],
  [SC_SID_SSO_AUTH_SUCCESS, { "args": 1, "state": "normal", "targets": 1, "title": "SSO Auth", "msg": "网关 %%1%% 的 SSO 身份验证成功" }],
  [SC_SID_SSO_AUTH_WV2_SETUP_ERROR, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO 身份验证失败。没有 WebView2 运行时。请先安装，然后再继续。" }],
  [SC_SID_SSO_AUTH_FQDN_NAVIGATION_FAILED, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "无法完成网关 %%1%% 的 SSO 身份验证" }],
  [SC_SID_SSO_AUTH_USER_EMBEDDED_BROWSER, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "因为用户关闭了对话框，网关 %%1%% 的 SSO 身份验证失败" }],
  [SC_SID_SSO_AUTH_INVALID_AUTH_RESPONSE, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "因为响应未包含所有必填字段，网关 %%1%% 的 SSO 身份验证失败" }],
  [SC_SID_SSO_AUTH_TIMEOUT, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "由于超时，网关 %%1%% 的 SSO 身份验证失败" }],
  [SC_SID_SSO_CLEAR_COOKIE_SUCCESS, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "SSO Cookie 已删除" }],
  [SC_SID_SSO_CLEAR_COOKIE_FAILED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "删除 SSO Cookie 失败" }],
  [SC_SID_SSO_COOKIE_NOTEXIST, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "未找到 SSO Cookie" }],
  [SC_SID_SSO_TRIGGER_AUTH, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_FORCE_SSO_RE_LOGIN_CONFIRM_MSG, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "下次连接时需要使用 SSO 登录" }],
  [SC_SID_SSO_NOT_ENABLED_PROV_GW, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "没有为预配网关 %%1%% 启用 SSO" }],
  [SC_SID_SSO_GATEWAY_UNREACHABLE, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO 网关 %%1%% 无法访问" }],
  [SC_SID_SSO_CERTIFICATE_REVOKED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "因为证书已停用，网关 %%1%% 的 SSO 身份验证失败" }],
  [SC_SID_SSO_CERTIFICATE_EXPIRED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "因为证书已过期，网关 %%1%% 的 SSO 身份验证失败" }],
  [SC_SID_SSO_NO_REACHABLE_ENABLED_PROV_GW, {"args": 0, "state": "error", "targets": 1, "title": "SSO Auth", "msg": "无法找到启用 SSO 身份验证的可访问预配网关" }],
  [SC_SID_SSO_TRIGGER_CONN, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_GATEWAY_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_SSO_AUTH_SERVICE_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
];