var statusMsgArray_pt_br = 
[
  [SC_SID_RESOLVE_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "A resolução DNS apresentou falha no gateway: %%1%%" }],
  [SC_SID_NO_INTERNET_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Sem conectividade com a Internet" }],
  [SC_SID_PING_SEND_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha no envio do ping" }],
  [SC_SID_PING_RECV_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha no recebimento do ping" }],
  [SC_SID_SOCK_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao criar socket" }],
  [SC_SID_SOCK_ADDR_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Informação de endereço ausente" }],
  [SC_SID_TIMEOUT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Tempo de espera expirou enquanto aguardava resposta do servidor" }],
  [SC_SID_ERRORED_OUT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Erro enquanto aguardava resposta do servidor" }],
  [SC_SID_INVALID_P2_ID, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Proposta de ID de Fase 2 inválida" }],
  [SC_SID_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Notificação NO_PROPOSAL_CHOSEN recebida do gateway: %%1%%" }],
  [SC_SID_CHILD_SA_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível estabelecer SA (Security Association) secundária" }],
  [SC_SID_ZIP_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível criar relatório de suporte técnico" }],
  [SC_SID_CONN_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao importar conexão" }],
  [SC_SID_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao importar certificado" }],
  [SC_SID_CERT_IMPORT_REQUIRED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "É necessário importar um certificado" }],
  [SC_SID_CONN_LIST_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao obter a lista de conexões" }],
  [SC_SID_NEED_AUTH_ERR, { "args": 0, "state": "normal", "targets": 1, "title": "Autenticação Requerida", "msg": "Insira as credenciais de usuário" }],
  [SC_SID_CONN_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao carregar conexão" }],
  [SC_SID_CERT_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao carregar certificado" }],
  [SC_SID_SWAN_CMD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha no envio do comando ao serviço IPsec" }],
  [SC_SID_SA_TERMINATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível encerrar SA (Security Association)" }],
  [SC_SID_SA_UNLOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível descarregar SA (Security Association)" }],
  [SC_SID_CONN_NOT_ENABLED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Conexão não habilitada" }],
  [SC_SID_INVALID_REQUEST, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Solicitação inválida" }],
  [SC_SID_CONN_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Conexão não encontrada" }],
  [SC_SID_CONN_FORMAT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "A conexão não pôde ser adicionada - configuração inválida" }],
  [SC_SID_CONN_PARSE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "A conexão não pôde ser analisada - formato desconhecido" }],
  [SC_SID_CONN_CONFIG_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "A conexão não pôde ser adicionada - formato inválido" }],
  [SC_SID_USER_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao importar certificado do usuário" }],
  [SC_SID_CA_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao importar certificado CA" }],
  [SC_SID_KEY_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao importar chave privada" }],
  [SC_SID_SVC_STOPPED_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "O serviço VPN foi interrompido" }],
  [SC_SID_IKE_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Notificação NO_PROPOSAL_CHOSEN IKE recebida do gateway: %%1%%" }],
  [SC_SID_INTERNAL_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Ocorreu um erro interno" }],
  [SC_SID_IKE_SEND_ERR, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_PSK_MISMATCH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "PSK incorreto" }],
  [SC_SID_IKE_NO_RESPONSE_ERR, { "args": 1, "state": "error", "targets": 3, "title": "Falha na conexão", "msg": "Sem resposta do gateway: %%1%%" }],
  [SC_SID_SENDING_DPD_REQUEST, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RECEIVED_DPD_ACK, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SENDING_IKE_DELETE, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_AUTH_CANCELLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Autenticação de usuário cancelada" }],
  [SC_SID_ERR_FILE_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "O arquivo especificado não foi encontrado" }],
  [SC_SID_ERR_CONN_EXISTS, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "A conexão %%1%% já existe" }],
  [SC_SID_ERR_TELEM_SEND, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_SVC_BUSY, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_HTTP_SEND, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_VPN_UNSTABLE, { "args": 1, "state": "warning", "targets": 7, "title": "Conexão instável", "msg": "A conexão %%1%% ficou instável" }],
  [SC_SID_DISABLED_UPON_WAKEUP, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Conexão %%1%% desabilitada após despertar do repouso" }],
  [SC_SID_DISABLED_BY_CLI, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "A conexão %%1%% foi desabilitada via interface de linha de comando" }],
  [SC_SID_DISABLED_BY_GATEWAY, { "args": 1, "state": "warning", "targets": 3, "title": "Conexão desabilitada", "msg": "A conexão foi desabilitada pelo gateway: %%1%%" }],
  [SC_SID_SA_NO_LONGER_EXISTS, { "args": 1, "state": "error", "targets": 3, "title": "Conexão desabilitada", "msg": "A conexão %%1%% foi desabilitada" }],
  [SC_SID_DISABLED_INTERFACE_DOWN, { "args": 1, "state": "warning", "targets": 3, "title": "Conexão desabilitada", "msg": "A conexão %%1%% foi desabilitada. Conectividade de rede perdida" }],
  [SC_SID_DPD_TIMEOUT, { "args": 1, "state": "warning", "targets": 7, "title": "", "msg": "Conexão perdida ao gateway: %%1%%" }],
  [SC_SID_IKE_FAILURE, { "args": 0, "state": "warning", "targets": 3, "title": "É possível que a conexão falhe", "msg": "A porta UDP do IKE parece estar bloqueada" }],
  [SC_SID_NO_INTERNET, { "args": 0, "state": "warning", "targets": 3, "title": "Rede indisponível", "msg": "Não há conexão disponível à Internet" }],
  [SC_SID_ESTABLISHING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Estabelecendo conexão de %%1%%" }],
  [SC_SID_CONNECTED, { "args": 1, "state": "connected", "targets": 7, "title": "Conexão estabelecida", "msg": "Conexão de %%1%% estabelecida" }],
  [SC_SID_CONN_NOT_RESTARTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Na rede interna - conexão de %%1%% não é necessária" }],
  [SC_SID_INITIATING_AUTOCONNECT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Iniciando a conexão automática de %%1%%" }],
  [SC_SID_AUTOIMPORT_SUCCESS, { "args": 2, "state": "normal", "targets": 1, "title": "", "msg": "A conexão %%1%% foi importada automaticamente do arquivo %%2%%" }],
  [SC_SID_AUTOIMPORT_FAILURE, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "A importação automática do arquivo %%1%% falhou" }],
  [SC_SID_CONN_LIST_CHANGED, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SERVICE_ENABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "O serviço VPN foi desabilitado" }],
  [SC_SID_SERVICE_UNAVAILABLE, { "args": 0, "state": "error", "targets": 3, "title": "Serviço indisponível", "msg": "Confirme que o serviço VPN está em execução" }],
  [SC_SID_ALREADY_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "A ação solicitada já está em andamento" }],
  [SC_SID_SWAN_CONNECT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível conectar-se ao strongSwan" }],
  [SC_SID_NO_AUTO_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "A conexão automática não está disponível" }],
  [SC_SID_INITALIZING, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Inicializando" }],
  [SC_SID_LAST_CONNECTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Última conexão %%1%%" }],
  [SC_SID_NEVER_CONNECTED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Nunca se conectou" }],
  [SC_SID_CONNECTED_TODAY, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Conectado hoje %%1%%" }],
  [SC_SID_CONNECTING, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Conectando %%1%% usando credenciais salvas" }],
  [SC_SID_CANCELLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Tentativa de conexão de %%1%% cancelada" }],
  [SC_SID_DISABLING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Desabilitando conexão de %%1%%" }],
  [SC_SID_DISABLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Conexão de %%1%% desabilitada" }],
  [SC_SID_CONNECTION_ALREADY_DISABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Conexão já desabilitada" }],
  [SC_SID_REMOVING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Removendo conexão de %%1%%" }],
  [SC_SID_CONNECTION_ADDED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Conexão de %%1%% adicionada" }],
  [SC_SID_CONNECTION_REMOVED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Conexão de %%1%% removida" }],
  [SC_SID_REMOVE_CONNECTION_CONFIRM, { "args": 1, "state": "warning", "targets": 2, "title": "", "msg": "Remover esta conexão: %%1%%?" }],
  [SC_SID_CERTIFICATE_IMPORTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Certificado importado para %%1%%" }],
  [SC_SID_ADDING_CONNECTION_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Adicionando arquivo de conexão %%1%%" }],
  [SC_SID_ADDING_CERTIFICATE_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Adicionando arquivo de certificado %%1%%" }],
  [SC_SID_PKCS12_ALERT, { "args": 0, "state": "warning", "targets": 2, "title": "Formato de arquivo incorreto", "msg": "Selecione um arquivo PKCS#12 para importar" }],
  [SC_SID_CERTIFICATE_IMPORT_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Falha na importação do certificado: %%1%%" }],
  [SC_SID_SC_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Versão do Sophos Connect: %%1%%" }],
  [SC_SID_SS_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Versão do strongSwan: %%1%%" }],
  [SC_SID_SS_VERSION_UNAVAILABLE, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "O serviço strongSwan não está disponível" }],
  [SC_SID_SYSTEM_ERR_MSG, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "Erro - código: %%1%% mensagem: %%2%%" }],
  [SC_SID_AUTH_SUCCEEDED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Autenticação bem-sucedida" }],
  [SC_SID_CLEARED_CREDENTIALS, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "As credenciais de usuário salvas para a conexão de %%1%% foram eliminadas" }],
  [SC_SID_CLEAR_CREDENTIALS_ERR, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Erro ao eliminar as credenciais de usuário salvas para a conexão de %%1%%" }],
  [SC_SID_MISSING_RESPONSE, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Resposta ausente" }],
  [SC_SID_MISSING_CONFIG_DATA, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Dados de configuração ausentes" }],
  [SC_SID_EDITED_CONNECTION_NAME, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Nome da conexão editado [%%1%%]" }],
  [SC_SID_CANCELLED_EDIT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Nome da conexão editado - edição cancelada [%%1%%]" }],
  [SC_SID_APP_QUIT_CONNFIRM, { "args": 1, "state": "normal", "targets": 2, "title": "", "msg": "Caso você continue, a conexão de %%1%% será desconectada. Deseja sair?" }],
  [SC_SID_NO_CONNECTIONS, { "args": 0, "state": "normal", "targets": 2, "title": "Sophos Connect", "msg": "Nenhuma conexão ainda. Importar uma conexão" }],
  [SC_SID_IMPORT_FILE_EMPTY_ERR, { "args": 1, "state": "error", "targets": 2, "title": "Erro de importação de arquivo", "msg": "Não foi possível importar o arquivo %%1%% porque ele está vazio" }],
  [SC_SID_IMPORT_FILE_SIZE_ERR, { "args": 1, "state": "error", "targets": 2, "title": "Erro de importação de arquivo", "msg": "O arquivo %%1%% ultrapassa o tamanho máximo de importação de arquivo de conexão" }],
  [SC_SID_ON_NETWORK, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Na rede interna. A conexão automática não é necessária" }],
  [SC_SID_AUTH_FAILED, { "args": 0, "state": "warning", "targets": 1, "title": "Falha na autenticação", "msg": "Houve falha na autenticação do usuário. Por favor, tente outra vez" }],
  [SC_SID_ADD_ROUTE_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "A falha ao adicionar a rota %%1%% impediu a conclusão da Fase 2" }],
  [SC_SID_INVALID_SERVER_CERT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível validar o certificado do servidor" }],
  [SC_SID_IDIR_MISMATCH_ERR, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "Discrepância de ID. Esperava-se %%1%%, mas foi recebido %%2%%" }],
  [SC_SID_NEED_OTP, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "É necessária uma senha de uso único" }],
  [SC_SID_NOT_PERMITTED_ERR, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "No momento, a ação solicitada não é permitida" }],
  [SC_SID_SSL_VPN_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Erro de VPN de SSL: %%1%%" }],
  [SC_SID_FILE_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao criar arquivo temporário" }],
  [SC_SID_SRV_DOWN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "O serviço OpenVPN não está disponível" }],
  [SC_SID_PIPE_WRITE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao gravar no pipe" }],
  [SC_SID_MGMT_SOCK_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "A porta de gerenciamento não está disponível" }],
  [SC_SID_UNTRUSTED_SERVER_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Não foi possível fazer a conexão com o servidor não confiável: %%1%%" }],
  [SC_SID_SERVER_CERT_CONFIRM, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "O certificado do servidor não pode ser verificado: %%1%%. Deseja continuar?" }],
  [SC_SID_DUPLICATE_CONNECTION, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "O arquivo de importação contém uma conexão em duplicata: %%1%%" }],
  [SC_SID_POLICY_GATEWAY_CONNECT_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Não é possível se conectar ao gateway da política: %%1%%" }],
  [SC_SID_NO_SSLVPN_POLICY_ERR, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "Nenhuma política de VPN de SSL está definida para este usuário: %%1%%" }],
  [SC_SID_BAD_COMPRESSION_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Erro de discrepância de compressão. Tentaremos uma nova conexão" }],
  [SC_SID_POLICY_UPLOAD_MSG, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Erro de discrepância de política. Baixaremos a política e tentaremos uma nova conexão" }],
  [SC_SID_POLICY_IMPORT_MSG, { "args": 0, "state": "error", "targets": 3, "title": "", "msg": "Erro de discrepância de política. Importar uma nova política para esta conexão" }],
  [SC_SID_SSL_CONNECTION_RESET, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "Recebida a redefinição de conexão do gateway: %%1%%" }],
  [SC_SID_NAME_LENGTH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "O nome da conexão não pode ter mais de 60 caracteres" }],
  [SC_SID_OPENVPN_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Versão do OpenVPN: %%1%%" }],
  [SC_SID_TRYING_TO_CONNECT, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Tentando estabelecer conexão com %%1%%" }],
  [SC_SID_GEN_1_ARG, { "args": 1, "state": "normal", "targets": 1, "title": "One argument", "msg": "A message with %%1%% required argument" }],
  [SC_SID_GEN_2_ARG, { "args": 2, "state": "warning", "targets": 5, "title": "Two arguments", "msg": "A message with %%1%% and %%2%% required arguments" }],
  [SC_SID_GEN_3_ARG, { "args": 3, "state": "error", "targets": 3, "title": "Three arguments", "msg": "A message with %%1%%, %%2%%, and %%3%% required arguments" }],
  [SC_SID_TEST_SYSTEM, { "args": 0, "state": "normal", "targets": 4, "title": "System", "msg": "A system message" }],
  [SC_SID_SSO_AUTH_SUCCESS, { "args": 1, "state": "normal", "targets": 1, "title": "SSO Auth", "msg": "A autenticação SSO foi bem-sucedida para o gateway %%1%%" }],
  [SC_SID_SSO_AUTH_WV2_SETUP_ERROR, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "Falha na autenticação SSO. O runtime WebView2 está ausente. Instale-o para continuar." }],
  [SC_SID_SSO_AUTH_FQDN_NAVIGATION_FAILED, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "A autenticação SSO não pôde ser concluída para o gateway %%1%%" }],
  [SC_SID_SSO_AUTH_USER_EMBEDDED_BROWSER, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "Falha na autenticação SSO para gateway %%1%% porque o usuário fechou a caixa de diálogo" }],
  [SC_SID_SSO_AUTH_INVALID_AUTH_RESPONSE, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "Falha na autenticação SSO para gateway %%1%% porque a resposta não contém todos os campos necessários" }],
  [SC_SID_SSO_AUTH_TIMEOUT, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "Falha na autenticação SSO para gateway %%1%% devido ao tempo limite" }],
  [SC_SID_SSO_CLEAR_COOKIE_SUCCESS, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Cookie SSO deletado" }],
  [SC_SID_SSO_CLEAR_COOKIE_FAILED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Falha ao deletar o cookie SSO" }],
  [SC_SID_SSO_COOKIE_NOTEXIST, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Nenhum cookie SSO encontrado" }],
  [SC_SID_SSO_TRIGGER_AUTH, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_FORCE_SSO_RE_LOGIN_CONFIRM_MSG, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "Requer logon SSO na próxima vez que você se conetar" }],
  [SC_SID_SSO_NOT_ENABLED_PROV_GW, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "O SSO não está habilitado para o gateway de provisionamento %%1%%" }],
  [SC_SID_SSO_GATEWAY_UNREACHABLE, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO do gateway %%1%% está inacessível" }],
  [SC_SID_SSO_CERTIFICATE_REVOKED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Falha na autenticação SSO do gateway %%1%% porque o certificado foi revogado" }],
  [SC_SID_SSO_CERTIFICATE_EXPIRED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Falha na autenticação SSO do gateway %%1%% porque o certificado expirou" }],
  [SC_SID_SSO_NO_REACHABLE_ENABLED_PROV_GW, {"args": 0, "state": "error", "targets": 1, "title": "SSO Auth", "msg": "Não foi possível encontrar um gateway de provisionamento acessível com a autenticação SSO habilitada" }],
  [SC_SID_SSO_TRIGGER_CONN, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_GATEWAY_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_SSO_AUTH_SERVICE_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
];