var statusMsgArray_ja_jp = 
[
  [SC_SID_RESOLVE_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "ゲートウェイで DNS 解決に失敗しました: %%1%%" }],
  [SC_SID_NO_INTERNET_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "インターネットに接続されていません" }],
  [SC_SID_PING_SEND_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "ping の送信に失敗しました。" }],
  [SC_SID_PING_RECV_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "ping の受信に失敗しました" }],
  [SC_SID_SOCK_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "ソケットの作成に失敗しました" }],
  [SC_SID_SOCK_ADDR_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "アドレス情報が見つかりません" }],
  [SC_SID_TIMEOUT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "サーバーの応答を待機中、タイムアウトしました" }],
  [SC_SID_ERRORED_OUT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "サーバーの応答を待機中、エラーが発生しました" }],
  [SC_SID_INVALID_P2_ID, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "無効なフェーズ 2 ID プロポーザルです" }],
  [SC_SID_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "ゲートウェイから通知 NO_PROPOSAL_CHOSEN を受信しました: %%1%%" }],
  [SC_SID_CHILD_SA_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "子 SA (セキュリティアソシエーション) の確立に失敗しました" }],
  [SC_SID_ZIP_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "テクニカルサポート レポートの生成に失敗しました" }],
  [SC_SID_CONN_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続のインポートに失敗しました" }],
  [SC_SID_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "証明書のインポートに失敗しました" }],
  [SC_SID_CERT_IMPORT_REQUIRED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "証明書のインポートが必要です" }],
  [SC_SID_CONN_LIST_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続リストの取得に失敗しました" }],
  [SC_SID_NEED_AUTH_ERR, { "args": 0, "state": "normal", "targets": 1, "title": "認証が必要です", "msg": "ユーザー認証情報を入力してください" }],
  [SC_SID_CONN_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続の読み込みに失敗しました" }],
  [SC_SID_CERT_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "証明書の読み込みに失敗しました" }],
  [SC_SID_SWAN_CMD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "IPsec サービスにコマンドを送信できませんでした" }],
  [SC_SID_SA_TERMINATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "SA (セキュリティアソシエーション) の終了に失敗しました" }],
  [SC_SID_SA_UNLOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "SA (セキュリティアソシエーション) のアンロードに失敗しました" }],
  [SC_SID_CONN_NOT_ENABLED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続が有効化されていません" }],
  [SC_SID_INVALID_REQUEST, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "無効なリクエストです" }],
  [SC_SID_CONN_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続が見つかりません" }],
  [SC_SID_CONN_FORMAT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続を追加できませんでした。無効な構成です" }],
  [SC_SID_CONN_PARSE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続を解析できませんでした。不明な形式です" }],
  [SC_SID_CONN_CONFIG_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続を追加できませんでした。無効な形式です" }],
  [SC_SID_USER_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "ユーザー証明書のインポートに失敗しました" }],
  [SC_SID_CA_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "ＣＡ 証明書のインポートに失敗しました" }],
  [SC_SID_KEY_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "秘密鍵のインポートに失敗しました" }],
  [SC_SID_SVC_STOPPED_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "VPN サービスが停止されました" }],
  [SC_SID_IKE_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "ゲートウェイから通知 IKE NO_PROPOSAL_CHOSEN を受信しました: %%1%%" }],
  [SC_SID_INTERNAL_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "内部エラーが発生しました" }],
  [SC_SID_IKE_SEND_ERR, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_PSK_MISMATCH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "PSK が正しくありません" }],
  [SC_SID_IKE_NO_RESPONSE_ERR, { "args": 1, "state": "error", "targets": 3, "title": "接続に失敗しました", "msg": "ゲートウェイから応答がありません: %%1%%" }],
  [SC_SID_SENDING_DPD_REQUEST, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RECEIVED_DPD_ACK, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SENDING_IKE_DELETE, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_AUTH_CANCELLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "ユーザーの認証がキャンセルされました" }],
  [SC_SID_ERR_FILE_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "指定したファイルが見つかりませんでした" }],
  [SC_SID_ERR_CONN_EXISTS, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "接続 %%1%% は既に存在します" }],
  [SC_SID_ERR_TELEM_SEND, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_SVC_BUSY, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_HTTP_SEND, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_VPN_UNSTABLE, { "args": 1, "state": "warning", "targets": 7, "title": "接続が不安定です", "msg": "接続 %%1%% が不安定になりました" }],
  [SC_SID_DISABLED_UPON_WAKEUP, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続 %%1%% はスリープから復帰した後、無効化されました" }],
  [SC_SID_DISABLED_BY_CLI, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続 %%1%% はコマンドラインインターフェースで無効化されました" }],
  [SC_SID_DISABLED_BY_GATEWAY, { "args": 1, "state": "warning", "targets": 3, "title": "接続が無効化されました", "msg": "接続はゲートウェイによって無効化されました: %%1%%" }],
  [SC_SID_SA_NO_LONGER_EXISTS, { "args": 1, "state": "error", "targets": 3, "title": "接続が無効化されました", "msg": "接続 %%1%% が無効化されました" }],
  [SC_SID_DISABLED_INTERFACE_DOWN, { "args": 1, "state": "warning", "targets": 3, "title": "接続が無効化されました", "msg": "接続 %%1%% が無効化されました。ネットワーク接続が失われました" }],
  [SC_SID_DPD_TIMEOUT, { "args": 1, "state": "warning", "targets": 7, "title": "", "msg": "ゲートウェイへの接続が失われました: %%1%%" }],
  [SC_SID_IKE_FAILURE, { "args": 0, "state": "warning", "targets": 3, "title": "接続に失敗する可能性があります", "msg": "IKE UDP ポートがブロックされている可能性があります" }],
  [SC_SID_NO_INTERNET, { "args": 0, "state": "warning", "targets": 3, "title": "ネットワークを使用できません", "msg": "使用できるインターネット接続がありません" }],
  [SC_SID_ESTABLISHING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続を確立しています: %%1%%" }],
  [SC_SID_CONNECTED, { "args": 1, "state": "connected", "targets": 7, "title": "接続を確立しました", "msg": "接続を確立しました: %%1%%" }],
  [SC_SID_CONN_NOT_RESTARTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "内部ネットワーク上にあります。接続 %%1%% は不要です" }],
  [SC_SID_INITIATING_AUTOCONNECT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "自動接続を開始しています: %%1%%" }],
  [SC_SID_AUTOIMPORT_SUCCESS, { "args": 2, "state": "normal", "targets": 1, "title": "", "msg": "接続 %%1%% は、ファイル %%2%% から自動インポートされました" }],
  [SC_SID_AUTOIMPORT_FAILURE, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "ファイル %%1%% の自動インポートに失敗しました" }],
  [SC_SID_CONN_LIST_CHANGED, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SERVICE_ENABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "VPN サービスが有効化されました" }],
  [SC_SID_SERVICE_UNAVAILABLE, { "args": 0, "state": "error", "targets": 3, "title": "サービスを使用できません", "msg": "VPN サービスが稼働中であることを確認してください" }],
  [SC_SID_ALREADY_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "リクエストされたアクションは既に実行中です" }],
  [SC_SID_SWAN_CONNECT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "strongSwan への接続に失敗しました" }],
  [SC_SID_NO_AUTO_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "自動接続を使用できません" }],
  [SC_SID_INITALIZING, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "初期化中です" }],
  [SC_SID_LAST_CONNECTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "前回の接続日時: %%1%%" }],
  [SC_SID_NEVER_CONNECTED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "未接続" }],
  [SC_SID_CONNECTED_TODAY, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "今日の接続日時: %%1%%" }],
  [SC_SID_CONNECTING, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "保存された認証情報を使用して %%1%% に接続しています" }],
  [SC_SID_CANCELLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続の試行をキャンセルしました: %%1%%" }],
  [SC_SID_DISABLING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続を無効化しています: %%1%%" }],
  [SC_SID_DISABLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続を無効化しました: %%1%%" }],
  [SC_SID_CONNECTION_ALREADY_DISABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "接続は既に無効化されています" }],
  [SC_SID_REMOVING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続を削除しています: %%1%%" }],
  [SC_SID_CONNECTION_ADDED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続を追加しました: %%1%%" }],
  [SC_SID_CONNECTION_REMOVED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続を削除しました: %%1%%" }],
  [SC_SID_REMOVE_CONNECTION_CONFIRM, { "args": 1, "state": "warning", "targets": 2, "title": "", "msg": "この接続を削除しますか: %%1%%？" }],
  [SC_SID_CERTIFICATE_IMPORTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "証明書をインポートしました: %%1%%" }],
  [SC_SID_ADDING_CONNECTION_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続ファイルを追加しています: %%1%%" }],
  [SC_SID_ADDING_CERTIFICATE_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "証明書ファイルを追加しています: %%1%%" }],
  [SC_SID_PKCS12_ALERT, { "args": 0, "state": "warning", "targets": 2, "title": "ファイル形式が正しくありません", "msg": "インポートする PKCS#12 ファイルを選択してください" }],
  [SC_SID_CERTIFICATE_IMPORT_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "証明書のインポートに失敗しました: %%1%%" }],
  [SC_SID_SC_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Sophos Connect バージョン: %%1%%" }],
  [SC_SID_SS_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "strongSwan バージョン: %%1%%" }],
  [SC_SID_SS_VERSION_UNAVAILABLE, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "strongSwan サービスを使用できません" }],
  [SC_SID_SYSTEM_ERR_MSG, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "エラー - コード: %%1%% メッセージ: %%2%%" }],
  [SC_SID_AUTH_SUCCEEDED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "認証に成功しました" }],
  [SC_SID_CLEARED_CREDENTIALS, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続に対する、保存されたユーザー認証情報を消去しました: %%1%%" }],
  [SC_SID_CLEAR_CREDENTIALS_ERR, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続に対する、保存されたユーザー認証情報を消去中、エラーが発生しました: %%1%%" }],
  [SC_SID_MISSING_RESPONSE, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "応答が見つかりません" }],
  [SC_SID_MISSING_CONFIG_DATA, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "構成データが見つかりません" }],
  [SC_SID_EDITED_CONNECTION_NAME, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "変更後の接続名: [%%1%%]" }],
  [SC_SID_CANCELLED_EDIT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "接続名の変更 - 編集をキャンセルしました: [%%1%%]" }],
  [SC_SID_APP_QUIT_CONNFIRM, { "args": 1, "state": "normal", "targets": 2, "title": "", "msg": "続行すると、接続 %%1%% は切断されます。終了しますか？" }],
  [SC_SID_NO_CONNECTIONS, { "args": 0, "state": "normal", "targets": 2, "title": "Sophos Connect", "msg": "接続していません。接続をインポートしてください" }],
  [SC_SID_IMPORT_FILE_EMPTY_ERR, { "args": 1, "state": "error", "targets": 2, "title": "ファイルインポートのエラー", "msg": "ファイル %%1%% は空のためインポートできません" }],
  [SC_SID_IMPORT_FILE_SIZE_ERR, { "args": 1, "state": "error", "targets": 2, "title": "ファイルインポートのエラー", "msg": "接続ファイル %%1%% は、インポートするファイルの最大サイズを超えています" }],
  [SC_SID_ON_NETWORK, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "内部ネットワーク上にあります。自動接続は不要です" }],
  [SC_SID_AUTH_FAILED, { "args": 0, "state": "warning", "targets": 1, "title": "認証に失敗しました", "msg": "ユーザーの認証に失敗しました。もう一度やり直してください" }],
  [SC_SID_ADD_ROUTE_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "ルート %%1%% の追加に失敗したため、フェーズ 2 を完了できませんでした" }],
  [SC_SID_INVALID_SERVER_CERT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "サーバー証明書の検証に失敗しました" }],
  [SC_SID_IDIR_MISMATCH_ERR, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "ID が一致しません。%%1%% を予期していましたが、%%2%% を受信しました。" }],
  [SC_SID_NEED_OTP, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "ワンタイムパスワードが必要です" }],
  [SC_SID_NOT_PERMITTED_ERR, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "リクエストされたアクションは、現在許可されていません" }],
  [SC_SID_SSL_VPN_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "SSL VPN エラー: %%1%%" }],
  [SC_SID_FILE_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "一時ファイルの作成に失敗しました" }],
  [SC_SID_SRV_DOWN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "OpenVPN サービスを使用できません" }],
  [SC_SID_PIPE_WRITE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "パイプへの書き込みに失敗しました" }],
  [SC_SID_MGMT_SOCK_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "管理ポートを使用できません" }],
  [SC_SID_UNTRUSTED_SERVER_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "信頼できないサーバーに接続できませんでした: %%1%%" }],
  [SC_SID_SERVER_CERT_CONFIRM, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "サーバー証明書を検証できません: %%1%%。続行しますか？" }],
  [SC_SID_DUPLICATE_CONNECTION, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "インポートファイルに重複した接続が含まれています: %%1%%" }],
  [SC_SID_POLICY_GATEWAY_CONNECT_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "ポリシーゲートウェイに接続できません: %%1%%" }],
  [SC_SID_NO_SSLVPN_POLICY_ERR, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "このユーザーに対して SSL VPN ポリシーが定義されていません: %%1%%" }],
  [SC_SID_BAD_COMPRESSION_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "圧縮の不一致エラー。接続を再試行します" }],
  [SC_SID_POLICY_UPLOAD_MSG, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "ポリシーの不一致エラー。ポリシーをダウンロードし、接続を再試行します" }],
  [SC_SID_POLICY_IMPORT_MSG, { "args": 0, "state": "error", "targets": 3, "title": "", "msg": "ポリシーの不一致エラー。この接続用に新しいポリシーをインポートします" }],
  [SC_SID_SSL_CONNECTION_RESET, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "ゲートウェイから接続リセットを受信しました: %%1%%" }],
  [SC_SID_NAME_LENGTH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "接続名は 60文字以内で入力してください" }],
  [SC_SID_OPENVPN_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "OpenVPN バージョン: %%1%%" }],
  [SC_SID_TRYING_TO_CONNECT, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "%%1%% に接続しようとしています" }],
  [SC_SID_GEN_1_ARG, { "args": 1, "state": "normal", "targets": 1, "title": "One argument", "msg": "A message with %%1%% required argument" }],
  [SC_SID_GEN_2_ARG, { "args": 2, "state": "warning", "targets": 5, "title": "Two arguments", "msg": "A message with %%1%% and %%2%% required arguments" }],
  [SC_SID_GEN_3_ARG, { "args": 3, "state": "error", "targets": 3, "title": "Three arguments", "msg": "A message with %%1%%, %%2%%, and %%3%% required arguments" }],
  [SC_SID_TEST_SYSTEM, { "args": 0, "state": "normal", "targets": 4, "title": "System", "msg": "A system message" }],
  [SC_SID_SSO_AUTH_SUCCESS, { "args": 1, "state": "normal", "targets": 1, "title": "SSO Auth", "msg": "ゲートウェイ %%1%% の SSO 認証に成功しました。" }],
  [SC_SID_SSO_AUTH_WV2_SETUP_ERROR, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO 認証に失敗しました。WebView2 ランタイムがありません。インストールして続行してください。" }],
  [SC_SID_SSO_AUTH_FQDN_NAVIGATION_FAILED, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "ゲートウェイ %%1%% の SSO 認証を完了できませんでした。" }],
  [SC_SID_SSO_AUTH_USER_EMBEDDED_BROWSER, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "ユーザーがダイアログを閉じたため、ゲートウェイ %%1%% の SSO 認証に失敗しました。" }],
  [SC_SID_SSO_AUTH_INVALID_AUTH_RESPONSE, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "応答にすべての必須フィールドが含まれていないため、ゲートウェイ %%1%% の SSO 認証に失敗しました。" }],
  [SC_SID_SSO_AUTH_TIMEOUT, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "タイムアウトのため、ゲートウェイ %%1%% の SSO 認証に失敗しました。" }],
  [SC_SID_SSO_CLEAR_COOKIE_SUCCESS, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "SSO クッキーが削除されました。" }],
  [SC_SID_SSO_CLEAR_COOKIE_FAILED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "SSO クッキーを削除できませんでした。" }],
  [SC_SID_SSO_COOKIE_NOTEXIST, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "SSO クッキーが見つかりません。" }],
  [SC_SID_SSO_TRIGGER_AUTH, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_FORCE_SSO_RE_LOGIN_CONFIRM_MSG, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "次回の接続時に SSO サインインが必要です" }],
  [SC_SID_SSO_NOT_ENABLED_PROV_GW, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO がプロビジョニングゲートウェイ %%1%% に対して有効になっていません" }],
  [SC_SID_SSO_GATEWAY_UNREACHABLE, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO ゲートウェイ %%1%% に到達できません" }],
  [SC_SID_SSO_CERTIFICATE_REVOKED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "証明書が失効しているため、ゲートウェイ %%1%% の SSO 認証に失敗しました" }],
  [SC_SID_SSO_CERTIFICATE_EXPIRED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "証明書の有効期限が切れているため、ゲートウェイ  %%1%%  の SSO 認証に失敗しました。" }],
  [SC_SID_SSO_NO_REACHABLE_ENABLED_PROV_GW, {"args": 0, "state": "error", "targets": 1, "title": "SSO Auth", "msg": "SSO 認証が有効になっている到達可能なプロビジョニングゲートウェイが見つかりませんでした" }],
  [SC_SID_SSO_TRIGGER_CONN, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_GATEWAY_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_SSO_AUTH_SERVICE_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
];