var statusMsgArray_en_us = 
[
  [SC_SID_RESOLVE_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "DNS resolution failed for gateway: %%1%%" }],
  [SC_SID_NO_INTERNET_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "No internet connectivity" }],
  [SC_SID_PING_SEND_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to send ping" }],
  [SC_SID_PING_RECV_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to receive ping" }],
  [SC_SID_SOCK_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to create socket" }],
  [SC_SID_SOCK_ADDR_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Missing address information" }],
  [SC_SID_TIMEOUT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Timed out waiting for server response" }],
  [SC_SID_ERRORED_OUT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Error waiting for server response" }],
  [SC_SID_INVALID_P2_ID, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Invalid Phase 2 ID proposal" }],
  [SC_SID_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Received NO_PROPOSAL_CHOSEN notification from gateway: %%1%%" }],
  [SC_SID_CHILD_SA_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to establish child SA (Security Association)" }],
  [SC_SID_ZIP_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to create technical support report" }],
  [SC_SID_CONN_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to import connection" }],
  [SC_SID_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to import certificate" }],
  [SC_SID_CERT_IMPORT_REQUIRED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Certificate import is required" }],
  [SC_SID_CONN_LIST_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to get connections list" }],
  [SC_SID_NEED_AUTH_ERR, { "args": 0, "state": "normal", "targets": 1, "title": "Authentication required", "msg": "Please enter user credentials" }],
  [SC_SID_CONN_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to load connection" }],
  [SC_SID_CERT_LOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to load certificate" }],
  [SC_SID_SWAN_CMD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to send command to IPsec service" }],
  [SC_SID_SA_TERMINATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to terminate SA (Security Association)" }],
  [SC_SID_SA_UNLOAD_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to unload SA (Security Association)" }],
  [SC_SID_CONN_NOT_ENABLED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Connection not enabled" }],
  [SC_SID_INVALID_REQUEST, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Invalid request" }],
  [SC_SID_CONN_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Connection not found" }],
  [SC_SID_CONN_FORMAT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "The connection could not be added - invalid configuration" }],
  [SC_SID_CONN_PARSE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "The connection could not be parsed - unknown format" }],
  [SC_SID_CONN_CONFIG_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "The connection could not be added - invalid format" }],
  [SC_SID_USER_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to import user certificate" }],
  [SC_SID_CA_CERT_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to import CA certificate" }],
  [SC_SID_KEY_IMPORT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to import private key" }],
  [SC_SID_SVC_STOPPED_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "VPN service has been stopped" }],
  [SC_SID_IKE_NO_PROPOSAL_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Received IKE NO_PROPOSAL_CHOSEN notification from gateway: %%1%%" }],
  [SC_SID_INTERNAL_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "An internal error occurred" }],
  [SC_SID_IKE_SEND_ERR, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_PSK_MISMATCH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Incorrect PSK" }],
  [SC_SID_IKE_NO_RESPONSE_ERR, { "args": 1, "state": "error", "targets": 3, "title": "Connection Failed", "msg": "No response from gateway: %%1%%" }],
  [SC_SID_SENDING_DPD_REQUEST, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RECEIVED_DPD_ACK, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SENDING_IKE_DELETE, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_AUTH_CANCELLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "User authentication cancelled" }],
  [SC_SID_ERR_FILE_NOT_FOUND, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "The specified file was not found" }],
  [SC_SID_ERR_CONN_EXISTS, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Connection %%1%% already exists" }],
  [SC_SID_ERR_TELEM_SEND, { "args": 0, "state": "error", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_SVC_BUSY, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_ERR_HTTP_SEND, { "args": 0, "state": "warning", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_VPN_UNSTABLE, { "args": 1, "state": "warning", "targets": 7, "title": "Connection unstable", "msg": "Connection %%1%% has become unstable" }],
  [SC_SID_DISABLED_UPON_WAKEUP, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Connection %%1%% disabled after wakeup from sleep" }],
  [SC_SID_DISABLED_BY_CLI, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Connection %%1%% was disabled via the command-line interface" }],
  [SC_SID_DISABLED_BY_GATEWAY, { "args": 1, "state": "warning", "targets": 3, "title": "Connection disabled", "msg": "Connection has been disabled by the gateway: %%1%%" }],
  [SC_SID_SA_NO_LONGER_EXISTS, { "args": 1, "state": "error", "targets": 3, "title": "Connection disabled", "msg": "Connection %%1%% has been disabled" }],
  [SC_SID_DISABLED_INTERFACE_DOWN, { "args": 1, "state": "warning", "targets": 3, "title": "Connection disabled", "msg": "Connection %%1%% has been disabled. Lost network connectivity" }],
  [SC_SID_DPD_TIMEOUT, { "args": 1, "state": "warning", "targets": 7, "title": "", "msg": "Connection lost to gateway: %%1%%" }],
  [SC_SID_IKE_FAILURE, { "args": 0, "state": "warning", "targets": 3, "title": "Connection may fail", "msg": "The IKE UDP port seems to be blocked" }],
  [SC_SID_NO_INTERNET, { "args": 0, "state": "warning", "targets": 3, "title": "Network unavailable", "msg": "No internet connection available" }],
  [SC_SID_ESTABLISHING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Establishing connection %%1%%" }],
  [SC_SID_CONNECTED, { "args": 1, "state": "connected", "targets": 7, "title": "Connection established", "msg": "Established connection %%1%%" }],
  [SC_SID_CONN_NOT_RESTARTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "On internal network - Connection %%1%% is not required" }],
  [SC_SID_INITIATING_AUTOCONNECT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Starting auto-connection for %%1%%" }],
  [SC_SID_AUTOIMPORT_SUCCESS, { "args": 2, "state": "normal", "targets": 1, "title": "", "msg": "Connection %%1%% was auto-imported from file %%2%%" }],
  [SC_SID_AUTOIMPORT_FAILURE, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Auto-import of file %%1%% failed" }],
  [SC_SID_CONN_LIST_CHANGED, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_SERVICE_ENABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "The VPN service has been enabled" }],
  [SC_SID_SERVICE_UNAVAILABLE, { "args": 0, "state": "error", "targets": 3, "title": "Service unavailable", "msg": "Please ensure the VPN service is running" }],
  [SC_SID_ALREADY_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "The requested action is already in progress" }],
  [SC_SID_SWAN_CONNECT_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to connect to strongSwan" }],
  [SC_SID_NO_AUTO_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Auto-connection is not available" }],
  [SC_SID_INITALIZING, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Initializing" }],
  [SC_SID_LAST_CONNECTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Last connected %%1%%" }],
  [SC_SID_NEVER_CONNECTED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Never connected" }],
  [SC_SID_CONNECTED_TODAY, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Connected today %%1%%" }],
  [SC_SID_CONNECTING, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Connecting %%1%% using saved credentials" }],
  [SC_SID_CANCELLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Cancelled connection attempt for %%1%%" }],
  [SC_SID_DISABLING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Disabling connection %%1%%" }],
  [SC_SID_DISABLED_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Disabled connection %%1%%" }],
  [SC_SID_CONNECTION_ALREADY_DISABLED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Connection already disabled" }],
  [SC_SID_REMOVING_CONNECTION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Removing connection %%1%%" }],
  [SC_SID_CONNECTION_ADDED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Added connection %%1%%" }],
  [SC_SID_CONNECTION_REMOVED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Removed connection %%1%%" }],
  [SC_SID_REMOVE_CONNECTION_CONFIRM, { "args": 1, "state": "warning", "targets": 2, "title": "", "msg": "Remove this connection: %%1%%?" }],
  [SC_SID_CERTIFICATE_IMPORTED, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Certificate imported for %%1%%" }],
  [SC_SID_ADDING_CONNECTION_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Adding connection file %%1%%" }],
  [SC_SID_ADDING_CERTIFICATE_FILE, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Adding certificate file %%1%%" }],
  [SC_SID_PKCS12_ALERT, { "args": 0, "state": "warning", "targets": 2, "title": "Incorrect file format", "msg": "Please select a PKCS#12 file for import" }],
  [SC_SID_CERTIFICATE_IMPORT_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Certificate import failed: %%1%%" }],
  [SC_SID_SC_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Sophos Connect version: %%1%%" }],
  [SC_SID_SS_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "strongSwan version: %%1%%" }],
  [SC_SID_SS_VERSION_UNAVAILABLE, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "The strongSwan service is unavailable" }],
  [SC_SID_SYSTEM_ERR_MSG, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "Error - code: %%1%% message: %%2%%" }],
  [SC_SID_AUTH_SUCCEEDED, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Authentication succeeded" }],
  [SC_SID_CLEARED_CREDENTIALS, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Cleared saved user credentials for connection %%1%%" }],
  [SC_SID_CLEAR_CREDENTIALS_ERR, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Error clearing saved user credentials for connection %%1%%" }],
  [SC_SID_MISSING_RESPONSE, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Missing response" }],
  [SC_SID_MISSING_CONFIG_DATA, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "Missing configuration data" }],
  [SC_SID_EDITED_CONNECTION_NAME, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Edited connection name [%%1%%]" }],
  [SC_SID_CANCELLED_EDIT, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "Edited connection name - cancelled edit [%%1%%]" }],
  [SC_SID_APP_QUIT_CONNFIRM, { "args": 1, "state": "normal", "targets": 2, "title": "", "msg": "If you continue, the connection %%1%% will be disconnected. Want to quit?" }],
  [SC_SID_NO_CONNECTIONS, { "args": 0, "state": "normal", "targets": 2, "title": "Sophos Connect", "msg": "No connections yet. Import a connection" }],
  [SC_SID_IMPORT_FILE_EMPTY_ERR, { "args": 1, "state": "error", "targets": 2, "title": "File import error", "msg": "File %%1%% cannot be imported because it is empty" }],
  [SC_SID_IMPORT_FILE_SIZE_ERR, { "args": 1, "state": "error", "targets": 2, "title": "File import error", "msg": "File %%1%% exceeds the maximum connection file import size" }],
  [SC_SID_ON_NETWORK, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "On internal network. Auto-connect not needed" }],
  [SC_SID_AUTH_FAILED, { "args": 0, "state": "warning", "targets": 1, "title": "Authentication failed", "msg": "User authentication failed. Please try again" }],
  [SC_SID_ADD_ROUTE_FAILED, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Failure to add route %%1%% prevented Phase 2 completion" }],
  [SC_SID_INVALID_SERVER_CERT, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to validate server certificate" }],
  [SC_SID_IDIR_MISMATCH_ERR, { "args": 2, "state": "error", "targets": 1, "title": "", "msg": "ID mismatch. Expected %%1%% but got %%2%%" }],
  [SC_SID_NEED_OTP, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "One-time password required" }],
  [SC_SID_NOT_PERMITTED_ERR, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "The requested action is not permitted at this time" }],
  [SC_SID_SSL_VPN_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "SSL VPN error: %%1%%" }],
  [SC_SID_FILE_CREATE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to create temporary file" }],
  [SC_SID_SRV_DOWN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "OpenVPN service is not available" }],
  [SC_SID_PIPE_WRITE_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to write to pipe" }],
  [SC_SID_MGMT_SOCK_CONN_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Management port is not available" }],
  [SC_SID_UNTRUSTED_SERVER_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Could not connect to untrusted server: %%1%%" }],
  [SC_SID_SERVER_CERT_CONFIRM, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Server certificate cannot be verified: %%1%%. Do you want to continue?" }],
  [SC_SID_DUPLICATE_CONNECTION, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Import file contains a duplicate connection: %%1%%" }],
  [SC_SID_POLICY_GATEWAY_CONNECT_ERR, { "args": 1, "state": "error", "targets": 1, "title": "", "msg": "Cannot connect to policy gateway: %%1%%" }],
  [SC_SID_NO_SSLVPN_POLICY_ERR, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "No SSL VPN policy is defined for this user: %%1%%" }],
  [SC_SID_BAD_COMPRESSION_ERR, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Compression mismatch error. Will retry connection" }],
  [SC_SID_POLICY_UPLOAD_MSG, { "args": 0, "state": "warning", "targets": 1, "title": "", "msg": "Policy mismatch error. Will download policy and retry connection. Please wait" }],
  [SC_SID_POLICY_IMPORT_MSG, { "args": 0, "state": "error", "targets": 3, "title": "", "msg": "Policy mismatch error. Import a new policy for this connection" }],
  [SC_SID_SSL_CONNECTION_RESET, { "args": 1, "state": "error", "targets": 3, "title": "", "msg": "Received connection reset from gateway: %%1%%" }],
  [SC_SID_NAME_LENGTH_ERR, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Connection name cannot be more than 60 characters" }],
  [SC_SID_OPENVPN_VERSION, { "args": 1, "state": "normal", "targets": 1, "title": "", "msg": "OpenVPN version: %%1%%" }],
  [SC_SID_TRYING_TO_CONNECT, { "args": 1, "state": "warning", "targets": 1, "title": "", "msg": "Trying to connect to gateway: %%1%%" }],
  [SC_SID_GEN_1_ARG, { "args": 1, "state": "normal", "targets": 1, "title": "One argument", "msg": "A message with %%1%% required argument" }],
  [SC_SID_GEN_2_ARG, { "args": 2, "state": "warning", "targets": 5, "title": "Two arguments", "msg": "A message with %%1%% and %%2%% required arguments" }],
  [SC_SID_GEN_3_ARG, { "args": 3, "state": "error", "targets": 3, "title": "Three arguments", "msg": "A message with %%1%%, %%2%%, and %%3%% required arguments" }],
  [SC_SID_TEST_SYSTEM, { "args": 0, "state": "normal", "targets": 4, "title": "System", "msg": "A system message" }],
  [SC_SID_SSO_AUTH_SUCCESS, { "args": 1, "state": "normal", "targets": 1, "title": "SSO Auth", "msg": "SSO authentication succeeded for gateway %%1%%" }],
  [SC_SID_SSO_AUTH_WV2_SETUP_ERROR, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO authentication failed. WebView2 runtime is missing. Please install it to continue." }],
  [SC_SID_SSO_AUTH_FQDN_NAVIGATION_FAILED, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO authentication could not complete for gateway %%1%%" }],
  [SC_SID_SSO_AUTH_USER_EMBEDDED_BROWSER, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO authentication failed for gateway %%1%% because user closed the dialog" }],
  [SC_SID_SSO_AUTH_INVALID_AUTH_RESPONSE, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO authentication failed for gateway %%1%% because response does not contain all required fields" }],
  [SC_SID_SSO_AUTH_TIMEOUT, { "args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO authentication failed for gateway %%1%% due to time-out" }],
  [SC_SID_SSO_CLEAR_COOKIE_SUCCESS, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "SSO cookie deleted" }],
  [SC_SID_SSO_CLEAR_COOKIE_FAILED, { "args": 0, "state": "error", "targets": 1, "title": "", "msg": "Failed to delete SSO cookie" }],
  [SC_SID_SSO_COOKIE_NOTEXIST, { "args": 0, "state": "normal", "targets": 1, "title": "", "msg": "No SSO cookie found" }],
  [SC_SID_SSO_TRIGGER_AUTH, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_FORCE_SSO_RE_LOGIN_CONFIRM_MSG, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "Requires SSO sign-in the next time you connect" }],
  [SC_SID_SSO_NOT_ENABLED_PROV_GW, {"args": 1, "state": "warning", "targets": 1, "title": "SSO Auth", "msg": "SSO isn't enabled for provisioning gateway %%1%%" }],
  [SC_SID_SSO_GATEWAY_UNREACHABLE, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO gateway %%1%% is unreachable" }],
  [SC_SID_SSO_CERTIFICATE_REVOKED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO authentication failed for gateway %%1%% because the certificate has been revoked" }],
  [SC_SID_SSO_CERTIFICATE_EXPIRED, {"args": 1, "state": "warning", "targets": 1, "title": "", "msg": "SSO authentication failed for gateway %%1%% because the certificate has expired" }],
  [SC_SID_SSO_NO_REACHABLE_ENABLED_PROV_GW, { "args": 0, "state": "error", "targets": 1, "title": "SSO Auth", "msg": "Couldn't find a reachable provisioning gateway with SSO authentication enabled" }],
  [SC_SID_SSO_TRIGGER_CONN, { "args": 3, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_GATEWAY_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
  [SC_SID_RETRY_SSO_AUTH_SERVICE_REACHABILITY, { "args": 0, "state": "normal", "targets": 0, "title": "", "msg": "" }],
];